# DICOM

In [131]:
# (0008, 0070) Manufacturer
import os, glob

global Manufacturer
Manufacturer = []

def print_recursiverly(path):
    try:
        is_dcm = all([pydicom.misc.is_dicom(j) for j in glob.glob(os.path.join(path, "*"))])
    except PermissionError:
        is_dcm = False
    
    if is_dcm:
        if len(glob.glob(os.path.join(path, "*"))) > 0:
            dcm = pydicom.dcmread(glob.glob(os.path.join(path, "*"))[0])
            if dcm.get((0x0008, 0x0060)).value == "CT":
                value = dcm.get((0x0008, 0x0070)).value
                print(value)
                type = "CBCT" if value == "ELEKTA" else "CT"
                Manufacturer.append({"type": type, "value": value, "path": path})
    else:
        for j in glob.glob(os.path.join(path, "*")):
            print_recursiverly(j)

for patient in glob.glob(os.path.join(r"c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data", "*")):
    print(patient)
    for i in glob.glob(os.path.join(patient, "*")):
        print_recursiverly(i)

c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\006
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips / MIM Software
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009
Philips
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011
Philips
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\012
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\013
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\014
Philips
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\015
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\016
Philips
Philips
Philips
Philips
Philips
Philips
GE MEDICAL SYSTEMS
GE MEDICAL SYSTEMS
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\017
Philips
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\018
Philips
Philips
GE MEDICAL SYSTEMS
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\019
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\021
Philips
Philips
SIEMENS
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\024
Philips
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\026
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\039
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
SIEMENS
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
SIEMENS
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\042
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
SIEMENS
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\128
Philips
Philips
ELEKTA
ELEKTA
ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\132
Philips
Philips
ELEKTA
ELEKTA
ELEKTA
ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\137
Philips
Philips
ELEKTA
ELEKTA
ELEKTA
ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\140
Philips
Philips
ELEKTA
ELEKTA
ELEKTA
ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\142
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\243
ELEKTA
ELEKTA
ELEKTA
ELEKTA
SIEMENS
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\245
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246
Philips
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\247
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\248
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\249
Philips
Philips
Philips
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\250
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\251
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\252
Philips
Philips
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\253
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\254
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\255
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\256
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\257
Philips / MIM Software
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\258
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\259
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\260
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\261
Philips
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\262
Philips
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263
Philips
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\264
Philips

In [135]:
for i in df["value"].unique():
    print(i)
    dff = df[df["value"] == i]
    for i, row in dff.iterrows():
        print(row["path"])

ELEKTA
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CBCT1
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CBCT2
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CBCT4
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CBCT5
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CBCT0
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CBCT4
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CBCT5
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CBCT1
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CBCT2
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CBCT3
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CBCT4
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CBCT5
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CBCT6
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CBCT0.030517
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CBCT1.100517
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CBCT2.150517
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CBCT3.220517
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CBCT4.290517
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CBCT5.030617
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CBCT5.120617
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CBCT0.060217
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CBCT0.310117
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CBCT1.130217
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CBCT2.200217
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CBCT3.280217
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CBCT4.060317
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CBCT5.140317
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CBCT0
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CBCT1
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CBCT2
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CBCT3
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CBCT4
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CBCT0
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CBCT2
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CBCT4
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CBCT5
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\039\CBCT1
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\039\CBCT2
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\039\CBCT3
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\039\CBCT4
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT1_060618
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT1_110618
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT1_180618
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT2_250618
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT3_030718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT4_090718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT4_180718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT6_240718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040\CBCT6_300718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041\CBCT0_140318
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041\CBCT0_190318
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041\CBCT1_260318
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041\CBCT2_030418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041\CBCT3_090418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041\CBCT4_160418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041\CBCT5_230418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\042\CBCT0\ANON\36146\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\042\CBCT1\ANON\36519\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\042\CBCT2\ANON\36667\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\042\CBCT3\ANON\36763\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\042\CBCT4\ANON\36835\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\042\CBCT5\ANON\36922\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT1_230118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT2_300118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT3_050218
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT4_120218
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT5_190218
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT_100118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT_150118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT_160118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043\CBCT_220118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044\CBCT0_040718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044\CBCT0_270618
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044\CBCT1_110718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044\CBCT2_180718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044\CBCT3_250718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044\CBCT4_010818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044\CBCT4_080818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045\CBCT0_280318
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045\CBCT1_030418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045\CBCT2_090418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045\CBCT3_160418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045\CBCT4_230418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045\CBCT5_070518
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045\CBCT5_300418
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046\CBCT0_221117
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046\CBCT0_281117
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046\CBCT1_041217
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046\CBCT2_111217
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046\CBCT3_181217
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046\CBCT4_291217
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046\CBCT5_030118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047\CBCT0_100118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047\CBCT0_150118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047\CBCT1_220118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047\CBCT2_290118
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047\CBCT3_050218
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047\CBCT4_120218
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047\CBCT5_190218
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048\CBCT0_040718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048\CBCT0_110718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048\CBCT1_180718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048\CBCT2_250718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048\CBCT3_010818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048\CBCT4_080818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048\CBCT5_130818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048\CBCT5_210818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117\CBCT_010818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117\CBCT_040718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117\CBCT_080818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117\CBCT_110718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117\CBCT_140818
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117\CBCT_180718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117\CBCT_250718
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\128\CBCT_070218\ANON\39388\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\128\CBCT_090118\ANON\38890\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\128\CBCT_180118\ANON\38890\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\132\CBCT\041017\2017-09__Studies\DOE^JOHN_ANON22555_CT_2017-09-08_095345_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\132\CBCT\111017\2017-09__Studies\DOE^JOHN_ANON22555_CT_2017-09-08_095345_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\132\CBCT\181017\2017-09__Studies\DOE^JOHN_ANON22555_CT_2017-09-08_095345_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\132\CBCT\200917\2017-09__Studies\DOE^JOHN_ANON22555_CT_2017-09-08_095345_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\137\CBCT_090617
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\137\CBCT_150717
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\137\CBCT_190617
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\137\CBCT_260617
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\140\CBCT_060617
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\140\CBCT_120617
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\140\CBCT_200617
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\140\CBCT_290517
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242\CBCT_040418\ANON\50832\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242\CBCT_080318\ANON\50832\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242\CBCT_140318\ANON\50832\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242\CBCT_150318\ANON\50832\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242\CBCT_200218\ANON\50832\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242\CBCT_210318\ANON\50832\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242\CBCT_280218\ANON\50832\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242\CBCT_280318\ANON\50832\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\243\CBCT_061121\ANON\MOSA_AC2\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\243\CBCT_141121\ANON\MOSA_AC2\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\243\CBCT_201121\ANON\MOSA_AC2\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\243\CBCT_311021\ANON\MOSA_AC2\CT
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246\CBCT\020518\2018-03__Studies\DOE^JANE_ANON59404_CT_2018-03-28_094750_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246\CBCT\060618\2018-03__Studies\DOE^JANE_ANON59404_CT_2018-03-28_094750_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246\CBCT\090518\2018-03__Studies\DOE^JANE_ANON59404_CT_2018-03-28_094750_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246\CBCT\160518\2018-03__Studies\DOE^JANE_ANON59404_CT_2018-03-28_094750_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246\CBCT\230518\2018-03__Studies\DOE^JANE_ANON59404_CT_2018-03-28_094750_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246\CBCT\250418\2018-03__Studies\DOE^JANE_ANON59404_CT_2018-03-28_094750_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246\CBCT\300518\2018-03__Studies\DOE^JANE_ANON59404_CT_2018-03-28_094750_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\261\CBCT\010318\2018-01__Studies\DOE^JOHN_ANON97273_CT_2018-01-26_152723_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\261\CBCT\070318\2018-01__Studies\DOE^JOHN_ANON97273_CT_2018-01-26_152723_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\261\CBCT\140218\2018-01__Studies\DOE^JOHN_ANON97273_CT_2018-01-26_152723_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\261\CBCT\140318\2018-01__Studies\DOE^JOHN_ANON97273_CT_2018-01-26_152723_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\261\CBCT\280318\2018-01__Studies\DOE^JOHN_ANON97273_CT_2018-01-26_152723_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\262\CBCT\070318\2018-01__Studies\DOE^JOHN_ANON11636_CT_2018-01-24_103331_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\262\CBCT\120218\2018-01__Studies\DOE^JOHN_ANON11636_CT_2018-01-24_103331_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\262\CBCT\120218\2018-01__Studies\DOE^JOHN_ANON11636_CT_2018-01-24_103331_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00001
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\262\CBCT\140318\2018-01__Studies\DOE^JOHN_ANON11636_CT_2018-01-24_103331_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\262\CBCT\190218\2018-01__Studies\DOE^JOHN_ANON11636_CT_2018-01-24_103331_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\262\CBCT\280218\2018-01__Studies\DOE^JOHN_ANON11636_CT_2018-01-24_103331_ORL.(sauf.sinus)_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\020518\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\040418\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\090518\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\110418\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\140518\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\160518\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\180418\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\230518\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263\CBCT\250418\2018-03__Studies\DOE^JOHN_ANON48826_CT_2018-03-29_094417_ORL.SIB.70-56.Gy_CBCT(#phase.-1).Option.1;.Max.slices..132_n132__00000
Philips
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT0\DOE^JOHN_ANON61841_CT_2017-06-21_100509_ORL.(sauf.sinus)_ORL.2MM_n198__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT1\DOE^JOHN_ANON61841_CT_2017-07-10_114626_ORL.(sauf.sinus)_ORL.2MM_n219__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT2\DOE^JOHN_ANON61841_CT_2017-07-17_114513_ORL.(sauf.sinus)_ORL.2MM_n201__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT3\DOE^JOHN_ANON61841_CT_2017-07-24_115628_ORL.(sauf.sinus)_ORL.2MM_n219__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT4\DOE^JOHN_ANON61841_CT_2017-07-31_113428_ORL.(sauf.sinus)_ORL.2MM_n217__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT5\DOE^JOHN_ANON61841_CT_2017-08-07_160502_ORL.(sauf.sinus)_ORL.2MM_n214__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT0\DOE^JOHN_ANON74898_CT_2017-05-31_092345_ORL.(sauf.sinus)_ORL.2MM_n207__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT1\DOE^JOHN_ANON74898_CT_2017-06-19_125915_ORL.(sauf.sinus)_ORL.2MM_n228__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT2\DOE^JOHN_ANON74898_CT_2017-06-26_124615_ORL.(sauf.sinus)_ORL.2MM_n199__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT3\DOE^JOHN_ANON74898_CT_2017-07-03_133230_ORL.(sauf.sinus)_ORL.2MM_n202__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT4\DOE^JOHN_ANON74898_CT_2017-07-10_133908_ORL.(sauf.sinus)_ORL.2MM_n203__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT5\DOE^JOHN_ANON74898_CT_2017-07-17_133250_ORL.(sauf.sinus)_ORL.2MM.ARTIX_n200__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT0\DOE^JOHN_ANON82870_CT_2017-04-12_110941_ORL.(sauf.sinus)_ORL.2MM_n205__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT1\DOE^JOHN_ANON82870_CT_2017-05-09_083939_ORL.(sauf.sinus)_ORL.2MM_n212__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT2\DOE^JOHN_ANON82870_CT_2017-05-15_115417_ORL.(sauf.sinus)_ORL.2MM_n201__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT3\DOE^JOHN_ANON82870_CT_2017-05-22_133154_ORL.(sauf.sinus)_ORL.2MM_n193__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT4\DOE^JOHN_ANON82870_CT_2017-05-29_101247_ORL.(sauf.sinus)_ORL.2MM_n207__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT5\DOE^JOHN_ANON82870_CT_2017-06-06_083719_ORL.(sauf.sinus)_ORL.2MM_n185__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT0\DOE^JOHN_ANON17151_CT_2017-03-30_174237_ORL.(sauf.sinus)_ORL.2MM_n211__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_CT_2017-05-02_124753_ORL.(sauf.sinus)_ORL.2MM_n216__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_CT_2017-05-09_140008_ORL.(sauf.sinus)_ORL.2MM_n224__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_CT_2017-05-15_114550_ORL.(sauf.sinus)_ORL.2MM_n211__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_CT_2017-05-22_123032_ORL.(sauf.sinus)_ORL.2MM_n209__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_CT_2017-05-29_120721_ORL.(sauf.sinus)_ORL.2MM_n235__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT0\DOE^JOHN_ANON22533_CT_2017-01-18_095403_ORL.(sauf.sinus)_ORL.2MM_n191__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT1\DOE^JOHN_ANON22533_CT_2017-02-06_131958_ORL.(sauf.sinus)_ORL.2MM_n200__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT2\DOE^JOHN_ANON22533_CT_2017-02-13_125803_ORL.(sauf.sinus)_ORL.2MM_n201__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT3\DOE^JOHN_ANON22533_CT_2017-02-20_111417_ORL.(sauf.sinus)_ORL.2MM_n197__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT4\DOE^JOHN_ANON22533_CT_2017-02-27_131827_ORL.(sauf.sinus)_ORL.2MM_n188__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT5\DOE^JOHN_ANON22533_CT_2017-03-06_130811_ORL.(sauf.sinus)_ORL.2MM_n187__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\006\CT0\2016-07__Studies\DOE^JOHN_ANON82513_CT_2016-07-06_162554_ORL.(sauf.sinus)_ORL.2MM_n185__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\006\CT1\DOE^JOHN_ANON82513_CT_2016-08-16_133352_ORL.(sauf.sinus)_ORL.2MM_n213__00000
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT0\DOE^JOHN_ANON31870_CT_2016-01-06_105717_ORL.(sauf.sinus)_ORL.2MM_n207__00000

In [134]:
import pandas
import plotly.express as px

df = pandas.DataFrame(Manufacturer)
for type in df["type"].unique():
    dff = df[df["type"] == type]
    dff = [{"type": k, "value": len(dff[dff["value"] == k])} for k in dff["value"].unique()]
    dff = pandas.DataFrame(dff)
    print(dff)

    fig = px.pie(dff, values='value', names='type')
    fig.show()

     type  value
0  ELEKTA    168

                     type  value
0                 Philips    228
1  Philips / MIM Software      2
2      GE MEDICAL SYSTEMS      3
3                 SIEMENS      5

In [59]:
from datetime import datetime

datetime_object = datetime.strptime(f[0x0008, 0x0012].value, '%Y%m%d')
print(datetime_object.day)

13

In [73]:
import glob, os

for i in glob.glob(os.path.join(r"c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004", "CT*")):
    print(i)
    for j in glob.glob(os.path.join(i, "*")):
        print(j)
        for k in glob.glob(os.path.join(j, "*"))[:1]:
            if pydicom.misc.is_dicom(k):
                dcm = pydicom.dcmread(k)
                print(datetime.strptime(dcm[0x0008, 0x0012].value, '%Y%m%d'))

c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT0
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT0\DOE^JOHN_ANON17151_CT_2017-03-30_174237_ORL.(sauf.sinus)_ORL.2MM_n211__00000
2017-03-30 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT0\DOE^JOHN_ANON17151_RTDOSE_2017-03-30_174237_ORL.(sauf.sinus)_CT.0.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT0\DOE^JOHN_ANON17151_RTPLAN_2017-03-30_174237_ORL.(sauf.sinus)_CT.0.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT0\DOE^JOHN_ANON17151_RTst_2017-03-30_174237_ORL.(sauf.sinus)_CT.0.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_CT_2017-05-02_124753_ORL.(sauf.sinus)_ORL.2MM_n216__00000
2017-05-02 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_RTDOSE_2017-05-02_124753_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_RTDOSE_2017-05-02_124753_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_RTPLAN_2017-05-02_124753_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_RTPLAN_2017-05-02_124753_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_RTst_2017-05-02_124753_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_CT_2017-05-09_140008_ORL.(sauf.sinus)_ORL.2MM_n224__00000
2017-05-09 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_RTDOSE_2017-05-09_140008_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_RTDOSE_2017-05-09_140008_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_RTPLAN_2017-05-09_140008_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_RTPLAN_2017-05-09_140008_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_RTst_2017-05-09_140008_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_CT_2017-05-15_114550_ORL.(sauf.sinus)_ORL.2MM_n211__00000
2017-05-15 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_RTDOSE_2017-05-15_114550_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_RTDOSE_2017-05-15_114550_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_RTPLAN_2017-05-15_114550_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_RTPLAN_2017-05-15_114550_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_RTst_2017-05-15_114550_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_CT_2017-05-22_123032_ORL.(sauf.sinus)_ORL.2MM_n209__00000
2017-05-22 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_RTDOSE_2017-05-22_123032_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_RTDOSE_2017-05-22_123032_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_RTPLAN_2017-05-22_123032_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_RTPLAN_2017-05-22_123032_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_RTst_2017-05-22_123032_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_CT_2017-05-29_120721_ORL.(sauf.sinus)_ORL.2MM_n235__00000
2017-05-29 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_RTDOSE_2017-05-29_120721_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_RTDOSE_2017-05-29_120721_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_RTPLAN_2017-05-29_120721_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_RTPLAN_2017-05-29_120721_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000
2017-10-13 00:00:00
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_RTst_2017-05-29_120721_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000
2017-10-13 00:00:00

In [91]:
global XCURRENT
XCURRENT = []

def print_recursiverly(path):
    try:
        is_dcm = all([pydicom.misc.is_dicom(j) for j in glob.glob(os.path.join(path, "*"))])
    except PermissionError:
        is_dcm = False
    
    if is_dcm:
        if len(glob.glob(os.path.join(path, "*"))) > 0:
            dcm = pydicom.dcmread(glob.glob(os.path.join(path, "*"))[0])
            if dcm.get((0x0008, 0x0060)).value == "CT":
                type = "CBCT" if "CBCT" in os.path.split(path)[1] else "CT"
                value = dcm.get((0x0018, 0x1151)).value
                print(value)
                XCURRENT.append({"type": type, "value": value})
    else:
        for j in glob.glob(os.path.join(path, "*")):
            print_recursiverly(j)

for patient in glob.glob(os.path.join(r"c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data", "*")):
    print(patient)
    for i in glob.glob(os.path.join(patient, "*")):
        print_recursiverly(i)

c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001
20
20
20
20
290
293
291
291
294
293
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002
20
20
20
285
290
289
294
285
292
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003
20
20
20
20
20
20
296
299
273
291
293
298
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004
20
20
20
20
20
20
20
295
292
294
293
291
291
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005
40
20
20
20
20
20
20
298
292
297
295
290
288
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\006
293
290
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007
10
10
10
10
10
298
294
271
298
297
293
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008
10
10
10
10
296
295
290
288
282
276
293
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009
294
295
298
295
301
298
299
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010
291
289
293
291
290
296
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011
290
293
291
291
293
294
292
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\012
294
290
292
293
293
289
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\013
294
292
290
291
292
290
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\014
294
290
292
291
292
298
292
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\015
299
295
283
295
294
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\016
296
297
301
299
301
296
29
29
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\017
260
293
290
293
291
296
290
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\018
299
295
29
296
296
299
298
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\019
299
301
296
301
297
303
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\021
300
300
108
301
297
296
300
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\024
279
305
291
276
279
296
280
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\026
299
297
292
300
295
296
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\039
20
20
20
20
287
287
286
286
288
294
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\040
20
20
20
20
20
20
20
20
20
38
286
287
295
290
291
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\041
20
20
20
20
20
20
20
296
293
290
296
292
75
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\042
20
20
20
20
20
20
291
293
294
296
294
290
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\043
20
20
20
20
20
20
20
20
20
292
293
293
299
290
288
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\044
20
20
20
20
20
20
20
273
296
303
296
261
295
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\045
20
20
20
20
20
20
20
297
283
291
292
31
294
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\046
20
20
20
20
20
20
20
293
295
303
293
295
300
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\047
20
20
20
20
20
20
20
294
292
293
291
292
292
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\048
20
20
20
20
20
20
20
20
293
289
289
283
297
269
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\117
20
20
20
20
20
20
20
294
286
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\128
287
292
20
20
20
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\132
296
288
20
20
20
20
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\137
293
294
20
20
20
20
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\140
291
292
20
20
20
20
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\142
290
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\242
20
20
20
20
20
20
20
20
294
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\243
20
20
20
20
23
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\245
299
295
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\246
288
20
20
20
20
20
20
20
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\247
289
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\248
294
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\249
299
303
299
302
298
298
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\250
300
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\251
291
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\252
290
298
297
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\253
295
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\254
295
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\255
298
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\256
295
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\257
274
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\258
290
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\259
292
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\260
293
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\261
295
20
20
20
20
20
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\262
290
20
20
20
20
20
20
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\263
297
20
20
20
20
20
20
20
20
20
c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\264
293

In [92]:
import pandas
import plotly.express as px
import plotly.figure_factory as ff

df = pandas.DataFrame(XCURRENT)

group_labels = ['CT', 'CBCT']
hist_data = [df[df["type"] == i]["value"] for i in group_labels]
fig = ff.create_distplot(hist_data, group_labels)
fig.show()

The tag (0020,0052) Frame of Reference UID is available in three different ways:
    (0020,0052) Frame of Reference UID
    (3006,0010) -> item -> (0020,0052) Frame of Reference UID
    (3006,0020) -> item -> (3006,0024) Referenced Frame of Reference UID

# clinical

In [47]:
import pandas

path_ = r"c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv"

df = pandas.read_csv(path_, delimiter=";")
df

,STUDYID,USUBJID,CENTERID,ARMCD,ACTARMCD,INCDT,RANDT,REPCPLT,REPDTC,BOREP1,...,CANCER2,CANCER2DT,CANCER2LOC,DDNDT,XERO12,XERO12_IMPUT1,XERO12_IMPUT2,ITT,MITT,PP
0,ARTIX,1,Rennes,Standard Arm,Standard Arm,05/07/2013,05/07/2013,Yes,01/10/2013,Progression,...,No,NaN,NaN,16/01/2014,A,NaN,No,Yes,Yes,Yes
1,ARTIX,2,Rennes,Replanification Arm,Replanification Arm,23/07/2013,25/07/2013,Yes,03/12/2013,Complete response,...,Yes,21/09/2015,Other,29/09/2015,No,No,No,Yes,Yes,Yes
2,ARTIX,4,Rennes,Replanification Arm,Replanification Arm,10/09/2013,18/09/2013,Yes,07/01/2014,Complete response,...,No,NaN,NaN,15/12/2015,No,No,No,Yes,Yes,Yes
3,ARTIX,9,Rennes,Standard Arm,Standard Arm,09/10/2013,18/10/2013,Yes,24/02/2014,Complete response,...,No,NaN,NaN,27/04/2016,NaN,NaN,No,Yes,Yes,Yes
4,ARTIX,14,Rennes,Replanification Arm,Replanification Arm,10/02/2014,19/02/2014,Yes,27/05/2014,Complete response,...,No,NaN,NaN,03/05/2016,No,No,No,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,ARTIX,124,Rennes,Replanification Arm,Replanification Arm,30/05/2018,01/06/2018,Yes,19/09/2018,Complete response,...,No,NaN,NaN,10/08/2020,Yes,Yes,Yes,Yes,Yes,Yes
61,ARTIX,126,Rennes,Standard Arm,Standard Arm,28/05/2018,22/06/2018,Yes,18/11/2019,Partial response,...,No,NaN,NaN,22/09/2020,Yes,Yes,Yes,Yes,Yes,Yes
62,ARTIX,127,Rennes,Standard Arm,Standard Arm,11/06/2018,27/06/2018,Yes,25/09/2018,Complete response,...,Yes,23/01/2020,Multi-site,14/08/2020,No,No,No,Yes,Yes,Yes
63,ARTIX,128,Rennes,Replanification Arm,Replanification Arm,11/06/2018,28/06/2018,No,NaN,Progression,...,No,NaN,NaN,09/01/2019,A,NaN,Yes,Yes,Yes,Yes
64,ARTIX,132,Rennes,Standard Arm,Standard Arm,01/10/2018,10/10/2018,Yes,29/01/2019,Complete response,...,No,NaN,NaN,08/12/2020,No,No,No,Yes,Yes,Yes

In [48]:
for i in df["XERO12_IMPUT1"].unique():
    if pandas.isna(i):
        n = len(df[pandas.isna(df["XERO12_IMPUT1"])])
    else:
        n = len(df[df["XERO12_IMPUT1"] == i])
    print(f"{i}: {n} ({100*n/len(df):.0f}%)")

nan: 22 (34%)
No: 27 (42%)
Yes: 16 (25%)

In [35]:
import pandas

df = pandas.read_csv(r"c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv", sep=";")
df = df[df["USUBJID"] == df["USUBJID"].unique()[2]]
df = df[df["MEASTYP"] == "Stimulated salivation flow"]
df

,STUDYID,USUBJID,CENTERID,ARMCD,ACTARMCD,INCDT,RANDT,MEASID,VISITID,MEASTYP,MEAS_VAL,MEAS_QUAL
128,ARTIX,4,Rennes,Replanification Arm,Replanification Arm,10/09/2013,18/09/2013,1,Inclusion,Stimulated salivation flow,680,NaN
165,ARTIX,4,Rennes,Replanification Arm,Replanification Arm,10/09/2013,18/09/2013,1,M6,Stimulated salivation flow,620,NaN
180,ARTIX,4,Rennes,Replanification Arm,Replanification Arm,10/09/2013,18/09/2013,1,M12,Stimulated salivation flow,740,NaN
203,ARTIX,4,Rennes,Replanification Arm,Replanification Arm,10/09/2013,18/09/2013,1,M18,Stimulated salivation flow,NaN,NaN
218,ARTIX,4,Rennes,Replanification Arm,Replanification Arm,10/09/2013,18/09/2013,1,M24,Stimulated salivation flow,NaN,NaN

In [36]:
df.columns

Index(['STUDYID', 'USUBJID', 'CENTERID', 'ARMCD', 'ACTARMCD', 'INCDT', 'RANDT',
       'MEASID', 'VISITID', 'MEASTYP', 'MEAS_VAL', 'MEAS_QUAL'],
      dtype='object')

# create ARTIX

In [1]:
import glob, os, tqdm
import artix

path = r"c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data"
patients = []
for p in tqdm.tqdm(glob.glob(os.path.join(path, "*")), ncols=50):
    patients.append(artix.load_patient(
        path=p,
        patient_description_csv=r"c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_PATIENT_DESCRIPTION_LTSI.csv",
        efficacy_csv=r"c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv",
        salivary_csv=r"c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv",
        ))

print(len(patients))

  0%|                      | 0/60 [00:00<?, ?it/s]

WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT1\DOE^JOHN_ANON61841_RTDOSE_2017-07-10_114626_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT1\DOE^JOHN_ANON61841_CT_2017-07-10_114626_ORL.(sauf.sinus)_ORL.2MM_n219__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT1\DOE^JOHN_ANON61841_RTDOSE_2017-07-10_114626_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT2\DOE^JOHN_ANON61841_RTDOSE_2017-07-17_114513_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT2\DOE^JOHN_ANON61841_CT_2017-07-17_114513_ORL.(sauf.sinus)_ORL.2MM_n201__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT2\DOE^JOHN_ANON61841_RTDOSE_2017-07-17_114513_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT3\DOE^JOHN_ANON61841_RTDOSE_2017-07-24_115628_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT3\DOE^JOHN_ANON61841_CT_2017-07-24_115628_ORL.(sauf.sinus)_ORL.2MM_n219__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT3\DOE^JOHN_ANON61841_RTDOSE_2017-07-24_115628_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT4\DOE^JOHN_ANON61841_RTDOSE_2017-07-31_113428_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT4\DOE^JOHN_ANON61841_CT_2017-07-31_113428_ORL.(sauf.sinus)_ORL.2MM_n217__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT4\DOE^JOHN_ANON61841_RTDOSE_2017-07-31_113428_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT5\DOE^JOHN_ANON61841_RTDOSE_2017-08-07_160502_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT5\DOE^JOHN_ANON61841_CT_2017-08-07_160502_ORL.(sauf.sinus)_ORL.2MM_n214__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\001\CT5\DOE^JOHN_ANON61841_RTDOSE_2017-08-07_160502_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000

  2%|▏             | 1/60 [00:21<21:33, 21.93s/it]

WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT2\DOE^JOHN_ANON74898_RTDOSE_2017-06-26_124615_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT2\DOE^JOHN_ANON74898_CT_2017-06-26_124615_ORL.(sauf.sinus)_ORL.2MM_n199__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT2\DOE^JOHN_ANON74898_RTDOSE_2017-06-26_124615_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT4\DOE^JOHN_ANON74898_RTDOSE_2017-07-10_133908_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT4\DOE^JOHN_ANON74898_CT_2017-07-10_133908_ORL.(sauf.sinus)_ORL.2MM_n203__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT4\DOE^JOHN_ANON74898_RTDOSE_2017-07-10_133908_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT5\DOE^JOHN_ANON74898_RTDOSE_2017-07-17_133250_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT5\DOE^JOHN_ANON74898_CT_2017-07-17_133250_ORL.(sauf.sinus)_ORL.2MM.ARTIX_n200__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\002\CT5\DOE^JOHN_ANON74898_RTDOSE_2017-07-17_133250_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000

  3%|▍             | 2/60 [00:42<20:40, 21.39s/it]

WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT3\DOE^JOHN_ANON82870_RTDOSE_2017-05-22_133154_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT3\DOE^JOHN_ANON82870_CT_2017-05-22_133154_ORL.(sauf.sinus)_ORL.2MM_n193__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\003\CT3\DOE^JOHN_ANON82870_RTDOSE_2017-05-22_133154_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000

  5%|▋             | 3/60 [00:57<17:33, 18.48s/it]

WARNING: patient folder id 3 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_PATIENT_DESCRIPTION_LTSI.csv
WARNING: patient folder id 3 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv
WARNING: patient folder id 3 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_RTDOSE_2017-05-02_124753_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_CT_2017-05-02_124753_ORL.(sauf.sinus)_ORL.2MM_n216__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT1\DOE^JOHN_ANON17151_RTDOSE_2017-05-02_124753_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_RTDOSE_2017-05-09_140008_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_CT_2017-05-09_140008_ORL.(sauf.sinus)_ORL.2MM_n224__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT2\DOE^JOHN_ANON17151_RTDOSE_2017-05-09_140008_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_RTDOSE_2017-05-15_114550_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_CT_2017-05-15_114550_ORL.(sauf.sinus)_ORL.2MM_n211__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT3\DOE^JOHN_ANON17151_RTDOSE_2017-05-15_114550_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_RTDOSE_2017-05-22_123032_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_CT_2017-05-22_123032_ORL.(sauf.sinus)_ORL.2MM_n209__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT4\DOE^JOHN_ANON17151_RTDOSE_2017-05-22_123032_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_RTDOSE_2017-05-29_120721_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_CT_2017-05-29_120721_ORL.(sauf.sinus)_ORL.2MM_n235__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\004\CT5\DOE^JOHN_ANON17151_RTDOSE_2017-05-29_120721_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000

  7%|▉             | 4/60 [01:21<18:58, 20.33s/it]

WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT1\DOE^JOHN_ANON22533_RTDOSE_2017-02-06_131958_VERSAHD.Treatmen.Tx.Plan.for.21700171.on.01-31-2017_CT.1.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT1\DOE^JOHN_ANON22533_CT_2017-02-06_131958_ORL.(sauf.sinus)_ORL.2MM_n200__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT1\DOE^JOHN_ANON22533_RTDOSE_2017-02-06_131958_VERSAHD.Treatmen.Tx.Plan.for.21700171.on.01-31-2017_CT.1.DOSI.1_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT2\DOE^JOHN_ANON22533_RTDOSE_2017-02-13_125803_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT2\DOE^JOHN_ANON22533_CT_2017-02-13_125803_ORL.(sauf.sinus)_ORL.2MM_n201__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT2\DOE^JOHN_ANON22533_RTDOSE_2017-02-13_125803_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT3\DOE^JOHN_ANON22533_RTDOSE_2017-02-20_111417_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT3\DOE^JOHN_ANON22533_CT_2017-02-20_111417_ORL.(sauf.sinus)_ORL.2MM_n197__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT3\DOE^JOHN_ANON22533_RTDOSE_2017-02-20_111417_VERSAHD.Treatmen.Tx.Plan.for.21700171.on.02-20-2017_._n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT4\DOE^JOHN_ANON22533_RTDOSE_2017-02-27_131827_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT4\DOE^JOHN_ANON22533_CT_2017-02-27_131827_ORL.(sauf.sinus)_ORL.2MM_n188__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT4\DOE^JOHN_ANON22533_RTDOSE_2017-02-27_131827_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT5\DOE^JOHN_ANON22533_RTDOSE_2017-03-06_130811_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT5\DOE^JOHN_ANON22533_CT_2017-03-06_130811_ORL.(sauf.sinus)_ORL.2MM_n187__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT5\DOE^JOHN_ANON22533_RTDOSE_2017-03-06_130811_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000
WARNING: RTSTRUCT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT3\DOE^JOHN_ANON22533_RTst_2017-02-20_111417_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT3\DOE^JOHN_ANON22533_CT_2017-02-20_111417_ORL.(sauf.sinus)_ORL.2MM_n197__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\005\CT3\DOE^JOHN_ANON22533_RTst_2017-02-20_111417_VERSAHD.Treatmen.Tx.Plan.for.21700171.on.02-20-2017_._n1__00000

  8%|█▏            | 5/60 [01:54<22:52, 24.96s/it]

WARNING: patient folder id 5 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_PATIENT_DESCRIPTION_LTSI.csv
WARNING: patient folder id 5 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv
WARNING: patient folder id 5 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv
WARNING: RTDOSE at c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\006\CT1\DOE^JOHN_ANON82513_RTDOSE_2016-08-16_133352_ORL.(sauf.sinus)_replanning_n1__00000 found no matching CT

 10%|█▍            | 6/60 [01:56<15:29, 17.22s/it]

WARNING: patient folder id 6 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_PATIENT_DESCRIPTION_LTSI.csv
WARNING: patient folder id 6 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv
WARNING: patient folder id 6 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT1\DOE^JOHN_ANON31870_RTDOSE_2016-01-26_123501_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT1\DOE^JOHN_ANON31870_CT_2016-01-26_123501_ORL.(sauf.sinus)_ORL.2MM_n187__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT1\DOE^JOHN_ANON31870_RTDOSE_2016-01-26_123501_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT2\DOE^JOHN_ANON31870_RTDOSE_2016-02-01_123807_ORL.(sauf.sinus)_CT2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT2\DOE^JOHN_ANON31870_CT_2016-02-01_123807_ORL.(sauf.sinus)_ORL.2MM_n201__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT2\DOE^JOHN_ANON31870_RTDOSE_2016-02-01_123807_ORL.(sauf.sinus)_CT2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT3\DOE^JOHN_ANON31870_RTDOSE_2016-02-08_131446_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT3\DOE^JOHN_ANON31870_CT_2016-02-08_131446_ORL.(sauf.sinus)_ORL.2MM_n198__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT3\DOE^JOHN_ANON31870_RTDOSE_2016-02-08_131446_ORL.(sauf.sinus)_CT3.DOSI.3_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT4\DOE^JOHN_ANON31870_RTDOSE_2016-02-15_121920_ORL.(sauf.sinus)_CT4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT4\DOE^JOHN_ANON31870_CT_2016-02-15_121920_ORL.(sauf.sinus)_ORL.2MM_n196__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT4\DOE^JOHN_ANON31870_RTDOSE_2016-02-15_121920_ORL.(sauf.sinus)_CT4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT5\DOE^JOHN_ANON31870_RTDOSE_2016-02-22_115218_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT5\DOE^JOHN_ANON31870_CT_2016-02-22_115218_ORL.(sauf.sinus)_SCANNER.5_n199__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\007\CT5\DOE^JOHN_ANON31870_RTDOSE_2016-02-22_115218_ORL.(sauf.sinus)_CT5.DOSI.5_n1__00000

 12%|█▋            | 7/60 [02:26<19:01, 21.55s/it]

WARNING: patient folder id 7 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_PATIENT_DESCRIPTION_LTSI.csv
WARNING: patient folder id 7 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv
WARNING: patient folder id 7 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT1\DOE^JOHN_ANON55454_RTDOSE_2016-01-04_132650_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT1\DOE^JOHN_ANON55454_CT_2016-01-04_132650_ORL.(sauf.sinus)_ORL.2MM_n205__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT1\DOE^JOHN_ANON55454_RTDOSE_2016-01-04_132650_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT2\DOE^JOHN_ANON55454_RTDOSE_2016-01-11_134129_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT2\DOE^JOHN_ANON55454_CT_2016-01-11_134129_ORL.(sauf.sinus)_ORL.2MM_n204__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT2\DOE^JOHN_ANON55454_RTDOSE_2016-01-11_134129_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT3\DOE^JOHN_ANON55454_RTDOSE_2016-01-18_132900_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT3\DOE^JOHN_ANON55454_CT_2016-01-18_132900_ORL.(sauf.sinus)_ORL.2MM_n189__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT3\DOE^JOHN_ANON55454_RTDOSE_2016-01-18_132900_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT4\DOE^JOHN_ANON55454_RTDOSE_2016-01-26_085252_ORL.(sauf.sinus)_CT4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT4\DOE^JOHN_ANON55454_CT_2016-01-26_085252_ORL.(sauf.sinus)_ORL.2MM_n206__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT4\DOE^JOHN_ANON55454_RTDOSE_2016-01-26_085252_ORL.(sauf.sinus)_CT4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT5\DOE^JOHN_ANON55454_RTDOSE_2016-02-01_134202_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT5\DOE^JOHN_ANON55454_CT_2016-02-01_134202_ORL.(sauf.sinus)_ORL.2MM_n195__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT5\DOE^JOHN_ANON55454_RTDOSE_2016-02-01_134202_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT6\DOE^JOHN_ANON26032_RTDOSE_2016-02-08_114934_ORL.(sauf.sinus)_CT6_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT6\DOE^JOHN_ANON26032_CT_2016-02-08_114934_ORL.(sauf.sinus)_ORL.2MM_n198__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\008\CT6\DOE^JOHN_ANON26032_RTDOSE_2016-02-08_114934_ORL.(sauf.sinus)_CT6_n1__00001

 13%|█▊            | 8/60 [03:15<26:00, 30.00s/it]

WARNING: patient folder id 8 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_PATIENT_DESCRIPTION_LTSI.csv
WARNING: patient folder id 8 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv
WARNING: patient folder id 8 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT1\DOE^JOHN_ANON76027_RTDOSE_2015-10-06_092629_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT1\DOE^JOHN_ANON76027_CT_2015-10-06_092629_ORL.(sauf.sinus)_ORL.2MM_n185__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT1\DOE^JOHN_ANON76027_RTDOSE_2015-10-06_092629_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT2\DOE^JOHN_ANON76027_RTDOSE_2015-10-12_130847_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT2\DOE^JOHN_ANON76027_CT_2015-10-12_130847_ORL.(sauf.sinus)_ORL.2MM_n206__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT2\DOE^JOHN_ANON76027_RTDOSE_2015-10-12_130847_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT3\DOE^JOHN_ANON76027_RTDOSE_2015-10-20_125802_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT3\DOE^JOHN_ANON76027_CT_2015-10-20_125802_ORL.(sauf.sinus)_ORL.2MM_n199__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT3\DOE^JOHN_ANON76027_RTDOSE_2015-10-20_125802_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT4\DOE^JOHN_ANON76027_RTDOSE_2015-10-26_115538_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT4\DOE^JOHN_ANON76027_CT_2015-10-26_115538_ORL.(sauf.sinus)_ORL.2MM_n210__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT4\DOE^JOHN_ANON76027_RTDOSE_2015-10-26_115538_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT5\DOE^JOHN_ANON76027_RTDOSE_2015-11-03_085618_ORL.(sauf.sinus)_CT5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT5\DOE^JOHN_ANON76027_CT_2015-11-03_085618_ORL.(sauf.sinus)_ORL.2MM_n204__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT5\DOE^JOHN_ANON76027_RTDOSE_2015-11-03_085618_ORL.(sauf.sinus)_CT5.DOSI.5_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT6\2015-11__Studies\DOE^JOHN_ANON40885_RTDOSE_2015-11-09_122316_ORL.(sauf.sinus)_CT6_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT6\2015-11__Studies\DOE^JOHN_ANON40885_CT_2015-11-09_122316_ORL.(sauf.sinus)_ORL.2MM_n202__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\009\CT6\2015-11__Studies\DOE^JOHN_ANON40885_RTDOSE_2015-11-09_122316_ORL.(sauf.sinus)_CT6_n1__00001

 15%|██            | 9/60 [03:49<26:48, 31.54s/it]

WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT1\DOE^JOHN_ANON65293_RTDOSE_2015-07-20_121913_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT1\DOE^JOHN_ANON65293_CT_2015-07-20_121913_ORL.(sauf.sinus)_ORL.2MM_n203__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT1\DOE^JOHN_ANON65293_RTDOSE_2015-07-20_121913_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT2\DOE^JOHN_ANON65293_RTDOSE_2015-07-27_121010_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT2\DOE^JOHN_ANON65293_CT_2015-07-27_121010_ORL.(sauf.sinus)_ORL.2MM_n213__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT2\DOE^JOHN_ANON65293_RTDOSE_2015-07-27_121010_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT3\DOE^JOHN_ANON65293_RTDOSE_2015-08-04_083905_ORL.(sauf.sinus)_CT.3.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT3\DOE^JOHN_ANON65293_CT_2015-08-04_083905_ORL.(sauf.sinus)_ORL.2MM_n211__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT3\DOE^JOHN_ANON65293_RTDOSE_2015-08-04_083905_ORL.(sauf.sinus)_CT.3.DOSI.3_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT4\DOE^JOHN_ANON65293_RTDOSE_2015-08-10_121811_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT4\DOE^JOHN_ANON65293_CT_2015-08-10_121811_ORL.(sauf.sinus)_ORL.2MM_n201__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT4\DOE^JOHN_ANON65293_RTDOSE_2015-08-10_121811_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT5\DOE^JOHN_ANON65293_RTDOSE_2015-08-17_124456_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT5\DOE^JOHN_ANON65293_CT_2015-08-17_124456_ORL.(sauf.sinus)_ORL.2MM_n234__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\010\CT5\DOE^JOHN_ANON65293_RTDOSE_2015-08-17_124456_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000

 17%|██▏          | 10/60 [04:15<24:44, 29.70s/it]

WARNING: patient folder id 10 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_PATIENT_DESCRIPTION_LTSI.csv
WARNING: patient folder id 10 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv
WARNING: patient folder id 10 not found in patient description CSV at c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT1\DOE^JOHN_ANON10669_RTDOSE_2015-05-12_084210_ORL.(sauf.sinus)_CT.1.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT1\DOE^JOHN_ANON10669_CT_2015-05-12_084210_ORL.(sauf.sinus)_ORL.2MM_n189__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT1\DOE^JOHN_ANON10669_RTDOSE_2015-05-12_084210_ORL.(sauf.sinus)_CT.1.DOSI.1_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT2\DOE^JOHN_ANON10669_RTDOSE_2015-05-18_124426_ORL.(sauf.sinus)_CT.2.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT2\DOE^JOHN_ANON10669_CT_2015-05-18_124426_ORL.(sauf.sinus)_ORL.2MM_n176__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT2\DOE^JOHN_ANON10669_RTDOSE_2015-05-18_124426_ORL.(sauf.sinus)_CT.2.DOSI.2_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT4\DOE^JOHN_ANON10669_RTDOSE_2015-06-01_124702_ORL.(sauf.sinus)_CT.4.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT4\DOE^JOHN_ANON10669_CT_2015-06-01_124702_ORL.(sauf.sinus)_ORL.2MM_n176__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT4\DOE^JOHN_ANON10669_RTDOSE_2015-06-01_124702_ORL.(sauf.sinus)_CT.4.DOSI.4_n1__00000
WARNING: RTDOSE c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT5\DOE^JOHN_ANON10669_RTDOSE_2015-06-09_084556_ORL.(sauf.sinus)_CT.5.DOSI.0_n1__00000 of CT c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT5\DOE^JOHN_ANON10669_CT_2015-06-09_084556_ORL.(sauf.sinus)_ORL.2MM_n190__00000 is being replaced by c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data\011\CT5\DOE^JOHN_ANON10669_RTDOSE_2015-06-09_084556_ORL.(sauf.sinus)_CT.5.DOSI.5_n1__00000

 17%|██▏          | 10/60 [04:45<23:46, 28.53s/it]

KeyboardInterrupt:

In [2]:
len(patients)

10

In [4]:
p = patients[8]
print(p.id)
print(len(p.ct))
print(len(p.cbct))

9
7
0

In [11]:
patients[7].clinical

{}

In [15]:
import pandas

df = pandas.read_csv(r"c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_PATIENT_DESCRIPTION_LTSI.csv", sep=";")
df["USUBJID"].unique()

array([  1,   2,   4,   9,  14,  16,  18,  21,  22,  23,  24,  25,  26,
        27,  29,  30,  31,  37,  38,  39,  41,  42,  43,  44,  50,  51,
        53,  57,  59,  63,  65,  72,  78,  79,  84,  87,  89,  90,  92,
        93,  94,  95,  96,  97,  98, 100, 101, 106, 107, 109, 110, 112,
       113, 114, 116, 117, 118, 119, 121, 123, 124, 126, 127, 128, 132],
      dtype=int64)

In [19]:
import pandas

df = pandas.read_csv(r"c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_EFFICACY_LTSI.csv", sep=";")
df["USUBJID"].unique()

array([  1,   2,   4,   9,  14,  16,  18,  21,  22,  23,  24,  25,  26,
        27,  29,  30,  31,  37,  38,  39,  41,  42,  43,  44,  50,  51,
        53,  57,  59,  63,  65,  72,  78,  79,  84,  87,  89,  90,  92,
        93,  94,  95,  96,  97,  98, 100, 101, 106, 107, 109, 110, 112,
       113, 114, 116, 117, 118, 119, 121, 123, 124, 126, 127, 128, 132],
      dtype=int64)

In [20]:
import pandas

df = pandas.read_csv(r"c:\Users\bguet\Desktop\data\ARTIX\toxicity_data\20241021_SALIVATION_DATA_LTSI.csv", sep=";")
df["USUBJID"].unique()

array([  1,   2,   4,   9,  14,  16,  18,  21,  22,  23,  24,  25,  26,
        27,  29,  30,  31,  37,  38,  39,  41,  42,  43,  44,  50,  51,
        53,  57,  59,  63,  65,  72,  78,  79,  84,  87,  89,  90,  92,
        93,  94,  95,  96,  97,  98, 100, 101, 106, 107, 109, 110, 112,
       113, 114, 116, 117, 118, 119, 121, 123, 124, 126, 127, 128, 132],
      dtype=int64)

In [27]:
patients = df["USUBJID"].unique().tolist()
p = os.listdir(r"c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data")

len(set(map(int, p)).intersection(set(map(int, patients))))

18

In [42]:
# Use this to map patients ID on csv to ID in ARTIX folder

id_map = pandas.read_excel(r"c:\Users\bguet\Desktop\data\ARTIX\ARTIX_ID_CORRELATION.xlsx")
id_map = id_map[["My Identifier ID", "USUBJID"]].astype(int, errors='ignore')
id_map

    My Identifier ID  USUBJID
0              247.0        1
1               26.0        2
2               24.0        4
3              248.0        9
4               21.0       14
..               ...      ...
60              44.0      124
61             117.0      126
62               NaN      127
63              48.0      128
64             243.0      132

[65 rows x 2 columns]

In [50]:
id_map["My Identifier ID"].unique()

array([247.,  26.,  24., 248.,  21.,  19.,  18., 249.,  16.,  17.,  15.,
       250.,  nan, 251.,  14.,  13., 252., 253.,  12., 254., 245.,  11.,
       255.,  10., 256., 257.,   9.,   8.,   7.,   6., 258., 259.,   5.,
       142., 260.,   4.,   3., 140., 137., 264.,   2.,   1.,  42., 132.,
        46., 128.,  47.,  43., 262., 261., 242.,  39.,  41.,  45., 263.,
       246.,  40.,  44., 117.,  48., 243.])

In [52]:
# all([float(i) in id_map["My Identifier ID"] 
for i in os.listdir(r"c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data"):
    print(i)
    print(float(i) in id_map["My Identifier ID"].unique())

001
True
002
True
003
True
004
True
005
True
006
True
007
True
008
True
009
True
010
True
011
True
012
True
013
True
014
True
015
True
016
True
017
True
018
True
019
True
021
True
024
True
026
True
039
True
040
True
041
True
042
True
043
True
044
True
045
True
046
True
047
True
048
True
117
True
128
True
132
True
137
True
140
True
142
True
242
True
243
True
245
True
246
True
247
True
248
True
249
True
250
True
251
True
252
True
253
True
254
True
255
True
256
True
257
True
258
True
259
True
260
True
261
True
262
True
263
True
264
True

In [53]:
print(all([float(i) in id_map["My Identifier ID"].unique() for i in os.listdir(r"c:\Users\bguet\Desktop\data\ARTIX\DICOM_ARTIX_data")]))

True