# Display features

In [2]:
import pickle
with open(r"C:\Users\bilel.guetarni\Desktop\ARTIX\data\artix.pkl", "rb") as f:
    patients = pickle.load(f)

In [10]:
print(patients[0].clinical.keys())
print(patients[0].id)
print(patients[0].clinical['SEX'])
print(patients[0].clinical['AGE'])
print(patients[0].clinical['ST_STAG'])
print(patients[0].clinical['ECOG'])

dict_keys(['STUDYID', 'USUBJID', 'CENTERID', 'ARMCD', 'ACTARMCD', 'INCDT', 'RANDT', 'SEX', 'AGE', 'BMI', 'ECOG', 'FUM', 'PA', 'OH', 'DIAB', 'SKIN', 'TTT', 'ATCD', 'P16', 'STAG', 'ST_STAG', 'ST_IMRT', 'ST_HPV', 'ST_CHEMO', 'HISTO', 'LAT', 'DIAM', 'NSTAG', 'GG', 'GG_SIZ', 'GG_NB', 'GG_FIX', 'LOC', 'ITT', 'MITT', 'PP', 'REPCPLT', 'REPDTC', 'BOREP1', 'ORR12', 'ORR24', 'DCD', 'DCDDT', 'DCDR', 'PROG', 'PROGDT', 'PROGLOC', 'PROGLR', 'PROGLRDT', 'CANCER2', 'CANCER2DT', 'CANCER2LOC', 'DDNDT', 'XERO12', 'XERO12_IMPUT1', 'XERO12_IMPUT2', 'TTSEQ', 'CHIMIO_TYP', 'CHIMIO_NB', 'CHIMIO_CUMUL', 'CHIMIO_CUMUL2', 'CHIMIOSTDT', 'CHIMIOENDDT', 'RTSTDT', 'RTENDT', 'RT_TYP', 'RT_NB', 'RT_INTER', 'COZ_INTER', 'SCAN_NB', 'SCAN_REPLDT', 'SCAN_REPLR', 'SCAN_REPLRP', 'SCAN_REPLSNUM', 'SCAN_REPLSDT'])
98
Male
49
Stage III
Completely ambulatory

In [9]:
import pandas
pandas.DataFrame(patients[0].clinical_measurements)

    type    value    visitID     sample
0    SSF     2820  Inclusion        NaN
1    SSF     1580         M6        NaN
2    SSF     1440        M12        NaN
3    SSF     1280        M18        NaN
4    SSF      980        M24        NaN
..   ...      ...        ...        ...
206   AE        0        M12  DYSPHAGIE
207   AE        0        M15  DYSPHAGIE
208   AE  Grade 1        M18  DYSPHAGIE
209   AE        0        M21  DYSPHAGIE
210   AE        0        M24  DYSPHAGIE

[211 rows x 4 columns]

In [12]:
import os
path_ = r"C:\Users\bilel.guetarni\Desktop\ARTIX\features\original\artix"
patient_folder = os.path.join(path_, [i for i in os.listdir(path_) if int(i) == int(patients[0].id)][0])
print(patient_folder)

C:\Users\bilel.guetarni\Desktop\ARTIX\features\original\artix\98

In [17]:
radiomics = pandas.read_csv(os.path.join(patient_folder, "deepnn.csv"))
radiomics["id"] = int(patients[0].id)
radiomics

      Unnamed: 0                              oar  name      value  id
0              0  inferior_pharyngeal_constrictor     0   1.364924  98
1              1  inferior_pharyngeal_constrictor     1   1.500968  98
2              2  inferior_pharyngeal_constrictor     2  -0.960994  98
3              3  inferior_pharyngeal_constrictor     3   1.712207  98
4              4  inferior_pharyngeal_constrictor     4 -11.100934  98
...          ...                              ...   ...        ...  ..
4603        4603                      oral_cavity   507  12.325427  98
4604        4604                      oral_cavity   508  16.845053  98
4605        4605                      oral_cavity   509  23.718340  98
4606        4606                      oral_cavity   510  15.559124  98
4607        4607                      oral_cavity   511   1.805484  98

[4608 rows x 5 columns]

In [ ]:
def load_features(path_, type_, patient_id, columns_to_keep=["oar", "name", "value"]):
    """
    load features

    args:
        path_ (str) path to features folder
        type_ (str) features type (radiomics, dosiomics, dvh, deepnn)
        patient_id (int,str) id of patient to find its folder
        columns_to_keep (list(str)) list of columns name to keep
    """
    patient_folder = os.path.join(path_, [i for i in os.listdir(path_) if int(i) == int(patient_id)][0])
    features = pandas.read_csv(os.path.join(patient_folder, f"{type_}.csv"))
    
    if "Unnamed: 0" in features.columns:
        features = features.drop(columns=["Unnamed: 0"])
    
    if columns_to_keep:
        features = features[columns_to_keep]
    
    return features

def load_radiomics(path_, patient_id, radiomics=["shape", "firstorder", "glcm", "gldm", "glrlm", "glszm", "ngtdm"]):
    df = load_features(path_, "radiomics", patient_id, columns_to_keep=None)
    df = df[(df["type"] == "original") & (df["class"].isin(radiomics))]
    return df.drop(columns=["type"])

def load_dosiomics(path_, patient_id, radiomics=["shape", "firstorder", "glcm", "gldm", "glrlm", "glszm", "ngtdm"]):
    df = load_features(path_, "dosiomics", patient_id, columns_to_keep=None)
    df = df[(df["type"] == "original") & (df["class"].isin(radiomics))]
    return df.drop(columns=["type"])

In [29]:
df = load_radiomics(path_, patients[0].id)
df

,oar,class,name,value,id
37,inferior_pharyngeal_constrictor,shape,Elongation,0.6332392723602007,98
38,inferior_pharyngeal_constrictor,shape,Flatness,0.17221602602169478,98
39,inferior_pharyngeal_constrictor,shape,LeastAxisLength,8.191254854755249,98
40,inferior_pharyngeal_constrictor,shape,MajorAxisLength,47.563836211871255,98
41,inferior_pharyngeal_constrictor,shape,Maximum2DDiameterColumn,44.41846462902562,98
...,...,...,...,...,...
1291,oral_cavity,ngtdm,Busyness,0.41364827812024374,98
1292,oral_cavity,ngtdm,Coarseness,0.00015605082009015784,98
1293,oral_cavity,ngtdm,Complexity,7699.555118661359,98
1294,oral_cavity,ngtdm,Contrast,0.002258607420755391,98
1295,oral_cavity,ngtdm,Strength,9.776568790005681,98

In [30]:
df = load_dosiomics(path_, patients[0].id)
df

,oar,class,name,value,id
37,inferior_pharyngeal_constrictor,shape,Elongation,0.6503859946301421,98
38,inferior_pharyngeal_constrictor,shape,Flatness,0.22645761555627789,98
39,inferior_pharyngeal_constrictor,shape,LeastAxisLength,10.951103391643514,98
40,inferior_pharyngeal_constrictor,shape,MajorAxisLength,48.35829152728146,98
41,inferior_pharyngeal_constrictor,shape,Maximum2DDiameterColumn,46.87216658103186,98
...,...,...,...,...,...
1291,oral_cavity,ngtdm,Busyness,135.46564239615049,98
1292,oral_cavity,ngtdm,Coarseness,0.0014106025927548165,98
1293,oral_cavity,ngtdm,Complexity,0.07725953792859573,98
1294,oral_cavity,ngtdm,Contrast,0.0042874171867065625,98
1295,oral_cavity,ngtdm,Strength,0.003933381778730391,98

In [22]:
df = load_features(path_, "dvh", patients[0].id)
df

                                 oar  name               value  id
0    inferior_pharyngeal_constrictor  mean  50.965553505535084  98
1    inferior_pharyngeal_constrictor   min               40.59  98
2    inferior_pharyngeal_constrictor   max               62.55  98
3    inferior_pharyngeal_constrictor   D98            42.41 Gy  98
4    inferior_pharyngeal_constrictor   D10            58.70 Gy  98
..                               ...   ...                 ...  ..
247                      oral_cavity   V55              0.00 %  98
248                      oral_cavity   V60              0.00 %  98
249                      oral_cavity   V65              0.00 %  98
250                      oral_cavity   V70              0.00 %  98
251                      oral_cavity   V75              0.00 %  98

[252 rows x 4 columns]

In [23]:
df = load_features(path_, "deepnn", patients[0].id)
df

                                  oar  name      value  id
0     inferior_pharyngeal_constrictor     0   1.364924  98
1     inferior_pharyngeal_constrictor     1   1.500968  98
2     inferior_pharyngeal_constrictor     2  -0.960994  98
3     inferior_pharyngeal_constrictor     3   1.712207  98
4     inferior_pharyngeal_constrictor     4 -11.100934  98
...                               ...   ...        ...  ..
4603                      oral_cavity   507  12.325427  98
4604                      oral_cavity   508  16.845053  98
4605                      oral_cavity   509  23.718340  98
4606                      oral_cavity   510  15.559124  98
4607                      oral_cavity   511   1.805484  98

[4608 rows x 4 columns]

# Build dataset

In [1]:
import pickle
with open(r"C:\Users\bilel.guetarni\Desktop\ARTIX\data\artix.pkl", "rb") as f:
    patients = pickle.load(f)

In [2]:
import pandas
import os

def load_features(path_, type_, patient_id, columns_to_keep=["oar", "name", "value"]):
    """
    load features

    args:
        path_ (str) path to features folder
        type_ (str) features type (radiomics, dosiomics, dvh, deepnn)
        patient_id (int,str) id of patient to find its folder
        columns_to_keep (list(str)) list of columns name to keep
    """
    patient_folder = os.path.join(path_, [i for i in os.listdir(path_) if int(i) == int(patient_id)][0])
    features = pandas.read_csv(os.path.join(patient_folder, f"{type_}.csv"))
    
    if "Unnamed: 0" in features.columns:
        features = features.drop(columns=["Unnamed: 0"])
    
    if columns_to_keep:
        features = features[columns_to_keep]
    
    return features

def load_radiomics(path_, patient_id, radiomics=["shape", "firstorder", "glcm", "gldm", "glrlm", "glszm", "ngtdm"]):
    df = load_features(path_, "radiomics", patient_id, columns_to_keep=None)
    df = df[(df["type"] == "original") & (df["class"].isin(radiomics))]
    return df.drop(columns=["type"])

def load_dosiomics(path_, patient_id, radiomics=["shape", "firstorder", "glcm", "gldm", "glrlm", "glszm", "ngtdm"]):
    df = load_features(path_, "dosiomics", patient_id, columns_to_keep=None)
    df = df[(df["type"] == "original") & (df["class"].isin(radiomics))]
    return df.drop(columns=["type"])

In [ ]:
import re

def transform_(x):
    if isinstance(x, str):
        digits = re.findall("\d", x)
        if len(digits) == 0:
            return None
        else:
            return int(digits[0])
    else:
        return None
    
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! adapt this for TCIA 
CLINICAL_MAPPING = {
    # SEX
    "Male": 1,
    "Female": 2,
    # "M": 1,
    # "F": 2,

    # CANCER STAGING
    "Stage III": 1,
    "Stage IVa": 2,
    "Stage IVb": 3,

    # ECOG
    "Asympatomatic": 0,
    "Completely ambulatory": 1,
    "lower than 50% in bed": 2,
}

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! adapt this for TCIA 
clinical = ['SEX', 'AGE', 'ST_STAG', 'ECOG']

features_path = r"C:\Users\bilel.guetarni\Desktop\ARTIX\features\original\artix"

df = []
for p in patients:
    patient_df = []

    for k in clinical:
        try:
            patient_df.append({"features": "clinical", "name": k, "value": int(p.clinical[k]), "id": int(p.id)})
        except ValueError:
            patient_df.append({"features": "clinical", "name": k, "value": CLINICAL_MAPPING[p.clinical[k]], "id": int(p.id)})

    # select dysphagia and xerostomia in CTCAE
    # transform values
    # change S0 into Inclusion
    # if patient has baseline tox, skip it
    # keep only M6 grade
    cm = pandas.DataFrame(p.clinical_measurements)
    cm = cm[(cm["type"] == "AE") & (cm["sample"].isin(["XEROSTOMIE", "DYSPHAGIE"]))]
    cm["value"] = cm["value"].apply(transform_)
    cm.loc[(cm["visitID"] == "S0"), "visitID"] = "Inclusion"
    if (cm[(cm["visitID"] == "Inclusion") & (cm["sample"] == "XEROSTOMIE")]["value"].astype('Int64') > 0).any():
        continue
    cm = cm[cm["visitID"] == "M6"]

    # transform tox value to binary
    cm.loc[(cm["value"] < 2), "value"] = 0
    cm.loc[(cm["value"] >= 2), "value"] = 1

    for _, row in cm.iterrows():
        patient_df.append({"features": "clinical", "name": row["sample"], "value": row["value"], "id": int(p.id)})

    try:
        # radiomics
        radiomics = load_radiomics(features_path, p.id)
        radiomics["id"] = int(p.id)
        radiomics["features"] = "radiomics"
        patient_df.extend(radiomics.to_dict(orient="records"))
    except (FileNotFoundError, IndexError):
        pass

    try:
        # dosiomics
        dosiomics = load_dosiomics(features_path, p.id)
        dosiomics["id"] = int(p.id)
        dosiomics["features"] = "dosiomics"
        patient_df.extend(dosiomics.to_dict(orient="records"))
    except (FileNotFoundError, IndexError):
        pass

    try:
        # dvh
        dvh = load_features(features_path, "dvh", p.id)
        dvh["id"] = int(p.id)
        dvh["features"] = "dvh"
        patient_df.extend(dvh.to_dict(orient="records"))
    except (FileNotFoundError, IndexError):
        pass

    try:
        # deepnn
        deepnn = load_features(features_path, "deepnn", p.id)
        deepnn["id"] = int(p.id)
        deepnn["features"] = "deepnn"
        patient_df.extend(deepnn.to_dict(orient="records"))
    except (FileNotFoundError, IndexError):
        pass

    df.extend(patient_df)

In [3]:
combined_path = r"C:\Users\bilel.guetarni\Desktop\tmp\artix_original.csv"
# pandas.DataFrame(df).to_csv(combined_path, index=False)

# Fit

In [4]:
import pandas
df = pandas.read_csv(combined_path)

In [5]:
# filter patients without xerostomia label
subdf = df[df["name"] == "XEROSTOMIE"]
subdf = subdf[pandas.isna(subdf["value"])]
patients_to_exclude = list(subdf["id"].unique())

# add patients without any XEROSTOMIA line
subdf = df[df["name"] == "XEROSTOMIE"]
patients_to_exclude.extend(list(set(set(df["id"].unique()).difference(subdf["id"].unique()))))

print("patients excluded due to absent xerostomia label:")
print(patients_to_exclude)

df = df[~df["id"].isin(patients_to_exclude)]

patients excluded due to absent xerostomia label:
[63, 59, 44, 29, 128, 107, 1, 25, 53, 113, 123]

FEATURES = {
    "clinical": ["SEX", "AGE", "ST_STAG", "ECOG"],
    "radiomics": ["shape", "firstorder", "glcm", "gldm", "glrlm", "glszm", "ngtdm"],
    "dosiomics": ["shape", "firstorder", "glcm", "gldm", "glrlm", "glszm", "ngtdm"],
    "dvh": ["mean", "min", "max", 
            "D98", "D10", "D20", "D30", "D40", "D50", "D60", "D70", "D80", "D90", 
            "V5", "V10", "V15", "V20", "V25", "V30", "V35", "V40", "V45", "V50", "V55", "V60", "V65", "V70", "V75"],
    "deepnn": "all",
}

In [6]:
list_of_features = df.groupby(["features", "class", "name"], dropna=False).size().reset_index().rename(columns={0:'count'})

missing_class_rows = filter(lambda row: pandas.isna(row[1]["class"]), list_of_features.iterrows())

with_class_rows = filter(lambda row: not(pandas.isna(row[1]["class"])), list_of_features.iterrows())

list_of_features = [
    *[f"{row['features']}_{row['name']}" for _, row in missing_class_rows],
    *[f"{row['features']}_{row['class']}_{row['name']}" for _, row in with_class_rows],
]

print(len(list_of_features))

760

In [44]:
list_of_features

['clinical_AGE',
 'clinical_DYSPHAGIE',
 'clinical_ECOG',
 'clinical_SEX',
 'clinical_ST_STAG',
 'clinical_XEROSTOMIE',
 'deepnn_0',
 'deepnn_1',
 'deepnn_10',
 'deepnn_100',
 'deepnn_101',
 'deepnn_102',
 'deepnn_103',
 'deepnn_104',
 'deepnn_105',
 'deepnn_106',
 'deepnn_107',
 'deepnn_108',
 'deepnn_109',
 'deepnn_11',
 'deepnn_110',
 'deepnn_111',
 'deepnn_112',
 'deepnn_113',
 'deepnn_114',
 'deepnn_115',
 'deepnn_116',
 'deepnn_117',
 'deepnn_118',
 'deepnn_119',
 'deepnn_12',
 'deepnn_120',
 'deepnn_121',
 'deepnn_122',
 'deepnn_123',
 'deepnn_124',
 'deepnn_125',
 'deepnn_126',
 'deepnn_127',
 'deepnn_128',
 'deepnn_129',
 'deepnn_13',
 'deepnn_130',
 'deepnn_131',
 'deepnn_132',
 'deepnn_133',
 'deepnn_134',
 'deepnn_135',
 'deepnn_136',
 'deepnn_137',
 'deepnn_138',
 'deepnn_139',
 'deepnn_14',
 'deepnn_140',
 'deepnn_141',
 'deepnn_142',
 'deepnn_143',
 'deepnn_144',
 'deepnn_145',
 'deepnn_146',
 'deepnn_147',
 'deepnn_148',
 'deepnn_149',
 'deepnn_15',
 'deepnn_150',
 'deepnn_151',
 'deepnn_152',
 'deepnn_153',
 'deepnn_154',
 'deepnn_155',
 'deepnn_156',
 'deepnn_157',
 'deepnn_158',
 'deepnn_159',
 'deepnn_16',
 'deepnn_160',
 'deepnn_161',
 'deepnn_162',
 'deepnn_163',
 'deepnn_164',
 'deepnn_165',
 'deepnn_166',
 'deepnn_167',
 'deepnn_168',
 'deepnn_169',
 'deepnn_17',
 'deepnn_170',
 'deepnn_171',
 'deepnn_172',
 'deepnn_173',
 'deepnn_174',
 'deepnn_175',
 'deepnn_176',
 'deepnn_177',
 'deepnn_178',
 'deepnn_179',
 'deepnn_18',
 'deepnn_180',
 'deepnn_181',
 'deepnn_182',
 'deepnn_183',
 'deepnn_184',
 'deepnn_185',
 'deepnn_186',
 'deepnn_187',
 'deepnn_188',
 'deepnn_189',
 'deepnn_19',
 'deepnn_190',
 'deepnn_191',
 'deepnn_192',
 'deepnn_193',
 'deepnn_194',
 'deepnn_195',
 'deepnn_196',
 'deepnn_197',
 'deepnn_198',
 'deepnn_199',
 'deepnn_2',
 'deepnn_20',
 'deepnn_200',
 'deepnn_201',
 'deepnn_202',
 'deepnn_203',
 'deepnn_204',
 'deepnn_205',
 'deepnn_206',
 'deepnn_207',
 'deepnn_208',
 'deepnn_209',
 'deepnn_21',
 'deepnn_210',
 'deepnn_211',
 'deepnn_212',
 'deepnn_213',
 'deepnn_214',
 'deepnn_215',
 'deepnn_216',
 'deepnn_217',
 'deepnn_218',
 'deepnn_219',
 'deepnn_22',
 'deepnn_220',
 'deepnn_221',
 'deepnn_222',
 'deepnn_223',
 'deepnn_224',
 'deepnn_225',
 'deepnn_226',
 'deepnn_227',
 'deepnn_228',
 'deepnn_229',
 'deepnn_23',
 'deepnn_230',
 'deepnn_231',
 'deepnn_232',
 'deepnn_233',
 'deepnn_234',
 'deepnn_235',
 'deepnn_236',
 'deepnn_237',
 'deepnn_238',
 'deepnn_239',
 'deepnn_24',
 'deepnn_240',
 'deepnn_241',
 'deepnn_242',
 'deepnn_243',
 'deepnn_244',
 'deepnn_245',
 'deepnn_246',
 'deepnn_247',
 'deepnn_248',
 'deepnn_249',
 'deepnn_25',
 'deepnn_250',
 'deepnn_251',
 'deepnn_252',
 'deepnn_253',
 'deepnn_254',
 'deepnn_255',
 'deepnn_256',
 'deepnn_257',
 'deepnn_258',
 'deepnn_259',
 'deepnn_26',
 'deepnn_260',
 'deepnn_261',
 'deepnn_262',
 'deepnn_263',
 'deepnn_264',
 'deepnn_265',
 'deepnn_266',
 'deepnn_267',
 'deepnn_268',
 'deepnn_269',
 'deepnn_27',
 'deepnn_270',
 'deepnn_271',
 'deepnn_272',
 'deepnn_273',
 'deepnn_274',
 'deepnn_275',
 'deepnn_276',
 'deepnn_277',
 'deepnn_278',
 'deepnn_279',
 'deepnn_28',
 'deepnn_280',
 'deepnn_281',
 'deepnn_282',
 'deepnn_283',
 'deepnn_284',
 'deepnn_285',
 'deepnn_286',
 'deepnn_287',
 'deepnn_288',
 'deepnn_289',
 'deepnn_29',
 'deepnn_290',
 'deepnn_291',
 'deepnn_292',
 'deepnn_293',
 'deepnn_294',
 'deepnn_295',
 'deepnn_296',
 'deepnn_297',
 'deepnn_298',
 'deepnn_299',
 'deepnn_3',
 'deepnn_30',
 'deepnn_300',
 'deepnn_301',
 'deepnn_302',
 'deepnn_303',
 'deepnn_304',
 'deepnn_305',
 'deepnn_306',
 'deepnn_307',
 'deepnn_308',
 'deepnn_309',
 'deepnn_31',
 'deepnn_310',
 'deepnn_311',
 'deepnn_312',
 'deepnn_313',
 'deepnn_314',
 'deepnn_315',
 'deepnn_316',
 'deepnn_317',
 'deepnn_318',
 'deepnn_319',
 'deepnn_32',
 'deepnn_320',
 'deepnn_321',
 'deepnn_322',
 'deepnn_323',
 'deepnn_324',
 'deepnn_325',
 'deepnn_326',
 'deepnn_327',
 'deepnn_328',
 'deepnn_329',
 'deepnn_33',
 'deepnn_330',
 'deepnn_331',
 'deepnn_332',
 'deepnn_333',
 'deepnn_334',
 'deepnn_335',
 'deepnn_336',
 'deepnn_337',
 'deepnn_338',
 'deepnn_339',
 'deepnn_34',
 'deepnn_340',
 'deepnn_341',
 'deepnn_342',
 'deepnn_343',
 'deepnn_344',
 'deepnn_345',
 'deepnn_346',
 'deepnn_347',
 'deepnn_348',
 'deepnn_349',
 'deepnn_35',
 'deepnn_350',
 'deepnn_351',
 'deepnn_352',
 'deepnn_353',
 'deepnn_354',
 'deepnn_355',
 'deepnn_356',
 'deepnn_357',
 'deepnn_358',
 'deepnn_359',
 'deepnn_36',
 'deepnn_360',
 'deepnn_361',
 'deepnn_362',
 'deepnn_363',
 'deepnn_364',
 'deepnn_365',
 'deepnn_366',
 'deepnn_367',
 'deepnn_368',
 'deepnn_369',
 'deepnn_37',
 'deepnn_370',
 'deepnn_371',
 'deepnn_372',
 'deepnn_373',
 'deepnn_374',
 'deepnn_375',
 'deepnn_376',
 'deepnn_377',
 'deepnn_378',
 'deepnn_379',
 'deepnn_38',
 'deepnn_380',
 'deepnn_381',
 'deepnn_382',
 'deepnn_383',
 'deepnn_384',
 'deepnn_385',
 'deepnn_386',
 'deepnn_387',
 'deepnn_388',
 'deepnn_389',
 'deepnn_39',
 'deepnn_390',
 'deepnn_391',
 'deepnn_392',
 'deepnn_393',
 'deepnn_394',
 'deepnn_395',
 'deepnn_396',
 'deepnn_397',
 'deepnn_398',
 'deepnn_399',
 'deepnn_4',
 'deepnn_40',
 'deepnn_400',
 'deepnn_401',
 'deepnn_402',
 'deepnn_403',
 'deepnn_404',
 'deepnn_405',
 'deepnn_406',
 'deepnn_407',
 'deepnn_408',
 'deepnn_409',
 'deepnn_41',
 'deepnn_410',
 'deepnn_411',
 'deepnn_412',
 'deepnn_413',
 'deepnn_414',
 'deepnn_415',
 'deepnn_416',
 'deepnn_417',
 'deepnn_418',
 'deepnn_419',
 'deepnn_42',
 'deepnn_420',
 'deepnn_421',
 'deepnn_422',
 'deepnn_423',
 'deepnn_424',
 'deepnn_425',
 'deepnn_426',
 'deepnn_427',
 'deepnn_428',
 'deepnn_429',
 'deepnn_43',
 'deepnn_430',
 'deepnn_431',
 'deepnn_432',
 'deepnn_433',
 'deepnn_434',
 'deepnn_435',
 'deepnn_436',
 'deepnn_437',
 'deepnn_438',
 'deepnn_439',
 'deepnn_44',
 'deepnn_440',
 'deepnn_441',
 'deepnn_442',
 'deepnn_443',
 'deepnn_444',
 'deepnn_445',
 'deepnn_446',
 'deepnn_447',
 'deepnn_448',
 'deepnn_449',
 'deepnn_45',
 'deepnn_450',
 'deepnn_451',
 'deepnn_452',
 'deepnn_453',
 'deepnn_454',
 'deepnn_455',
 'deepnn_456',
 'deepnn_457',
 'deepnn_458',
 'deepnn_459',
 'deepnn_46',
 'deepnn_460',
 'deepnn_461',
 'deepnn_462',
 'deepnn_463',
 'deepnn_464',
 'deepnn_465',
 'deepnn_466',
 'deepnn_467',
 'deepnn_468',
 'deepnn_469',
 'deepnn_47',
 'deepnn_470',
 'deepnn_471',
 'deepnn_472',
 'deepnn_473',
 'deepnn_474',
 'deepnn_475',
 'deepnn_476',
 'deepnn_477',
 'deepnn_478',
 'deepnn_479',
 'deepnn_48',
 'deepnn_480',
 'deepnn_481',
 'deepnn_482',
 'deepnn_483',
 'deepnn_484',
 'deepnn_485',
 'deepnn_486',
 'deepnn_487',
 'deepnn_488',
 'deepnn_489',
 'deepnn_49',
 'deepnn_490',
 'deepnn_491',
 'deepnn_492',
 'deepnn_493',
 'deepnn_494',
 'deepnn_495',
 'deepnn_496',
 'deepnn_497',
 'deepnn_498',
 'deepnn_499',
 'deepnn_5',
 'deepnn_50',
 'deepnn_500',
 'deepnn_501',
 'deepnn_502',
 'deepnn_503',
 'deepnn_504',
 'deepnn_505',
 'deepnn_506',
 'deepnn_507',
 'deepnn_508',
 'deepnn_509',
 'deepnn_51',
 'deepnn_510',
 'deepnn_511',
 'deepnn_52',
 'deepnn_53',
 'deepnn_54',
 'deepnn_55',
 'deepnn_56',
 'deepnn_57',
 'deepnn_58',
 'deepnn_59',
 'deepnn_6',
 'deepnn_60',
 'deepnn_61',
 'deepnn_62',
 'deepnn_63',
 'deepnn_64',
 'deepnn_65',
 'deepnn_66',
 'deepnn_67',
 'deepnn_68',
 'deepnn_69',
 'deepnn_7',
 'deepnn_70',
 'deepnn_71',
 'deepnn_72',
 'deepnn_73',
 'deepnn_74',
 'deepnn_75',
 'deepnn_76',
 'deepnn_77',
 'deepnn_78',
 'deepnn_79',
 'deepnn_8',
 'deepnn_80',
 'deepnn_81',
 'deepnn_82',
 'deepnn_83',
 'deepnn_84',
 'deepnn_85',
 'deepnn_86',
 'deepnn_87',
 'deepnn_88',
 'deepnn_89',
 'deepnn_9',
 'deepnn_90',
 'deepnn_91',
 'deepnn_92',
 'deepnn_93',
 'deepnn_94',
 'deepnn_95',
 'deepnn_96',
 'deepnn_97',
 'deepnn_98',
 'deepnn_99',
 'dvh_D10',
 'dvh_D20',
 'dvh_D30',
 'dvh_D40',
 'dvh_D50',
 'dvh_D60',
 'dvh_D70',
 'dvh_D80',
 'dvh_D90',
 'dvh_D98',
 'dvh_V10',
 'dvh_V15',
 'dvh_V20',
 'dvh_V25',
 'dvh_V30',
 'dvh_V35',
 'dvh_V40',
 'dvh_V45',
 'dvh_V5',
 'dvh_V50',
 'dvh_V55',
 'dvh_V60',
 'dvh_V65',
 'dvh_V70',
 'dvh_V75',
 'dvh_max',
 'dvh_mean',
 'dvh_min',
 'dosiomics_firstorder_10Percentile',
 'dosiomics_firstorder_90Percentile',
 'dosiomics_firstorder_Energy',
 'dosiomics_firstorder_Entropy',
 'dosiomics_firstorder_InterquartileRange',
 'dosiomics_firstorder_Kurtosis',
 'dosiomics_firstorder_Maximum',
 'dosiomics_firstorder_Mean',
 'dosiomics_firstorder_MeanAbsoluteDeviation',
 'dosiomics_firstorder_Median',
 'dosiomics_firstorder_Minimum',
 'dosiomics_firstorder_Range',
 'dosiomics_firstorder_RobustMeanAbsoluteDeviation',
 'dosiomics_firstorder_RootMeanSquared',
 'dosiomics_firstorder_Skewness',
 'dosiomics_firstorder_TotalEnergy',
 'dosiomics_firstorder_Uniformity',
 'dosiomics_firstorder_Variance',
 'dosiomics_glcm_Autocorrelation',
 'dosiomics_glcm_ClusterProminence',
 'dosiomics_glcm_ClusterShade',
 'dosiomics_glcm_ClusterTendency',
 'dosiomics_glcm_Contrast',
 'dosiomics_glcm_Correlation',
 'dosiomics_glcm_DifferenceAverage',
 'dosiomics_glcm_DifferenceEntropy',
 'dosiomics_glcm_DifferenceVariance',
 'dosiomics_glcm_Id',
 'dosiomics_glcm_Idm',
 'dosiomics_glcm_Idmn',
 'dosiomics_glcm_Idn',
 'dosiomics_glcm_Imc1',
 'dosiomics_glcm_Imc2',
 'dosiomics_glcm_InverseVariance',
 'dosiomics_glcm_JointAverage',
 'dosiomics_glcm_JointEnergy',
 'dosiomics_glcm_JointEntropy',
 'dosiomics_glcm_MCC',
 'dosiomics_glcm_MaximumProbability',
 'dosiomics_glcm_SumAverage',
 'dosiomics_glcm_SumEntropy',
 'dosiomics_glcm_SumSquares',
 'dosiomics_gldm_DependenceEntropy',
 'dosiomics_gldm_DependenceNonUniformity',
 'dosiomics_gldm_DependenceNonUniformityNormalized',
 'dosiomics_gldm_DependenceVariance',
 'dosiomics_gldm_GrayLevelNonUniformity',
 'dosiomics_gldm_GrayLevelVariance',
 'dosiomics_gldm_HighGrayLevelEmphasis',
 'dosiomics_gldm_LargeDependenceEmphasis',
 'dosiomics_gldm_LargeDependenceHighGrayLevelEmphasis',
 'dosiomics_gldm_LargeDependenceLowGrayLevelEmphasis',
 'dosiomics_gldm_LowGrayLevelEmphasis',
 'dosiomics_gldm_SmallDependenceEmphasis',
 'dosiomics_gldm_SmallDependenceHighGrayLevelEmphasis',
 'dosiomics_gldm_SmallDependenceLowGrayLevelEmphasis',
 'dosiomics_glrlm_GrayLevelNonUniformity',
 'dosiomics_glrlm_GrayLevelNonUniformityNormalized',
 'dosiomics_glrlm_GrayLevelVariance',
 'dosiomics_glrlm_HighGrayLevelRunEmphasis',
 'dosiomics_glrlm_LongRunEmphasis',
 'dosiomics_glrlm_LongRunHighGrayLevelEmphasis',
 'dosiomics_glrlm_LongRunLowGrayLevelEmphasis',
 'dosiomics_glrlm_LowGrayLevelRunEmphasis',
 'dosiomics_glrlm_RunEntropy',
 'dosiomics_glrlm_RunLengthNonUniformity',
 'dosiomics_glrlm_RunLengthNonUniformityNormalized',
 'dosiomics_glrlm_RunPercentage',
 'dosiomics_glrlm_RunVariance',
 'dosiomics_glrlm_ShortRunEmphasis',
 'dosiomics_glrlm_ShortRunHighGrayLevelEmphasis',
 'dosiomics_glrlm_ShortRunLowGrayLevelEmphasis',
 'dosiomics_glszm_GrayLevelNonUniformity',
 'dosiomics_glszm_GrayLevelNonUniformityNormalized',
 'dosiomics_glszm_GrayLevelVariance',
 'dosiomics_glszm_HighGrayLevelZoneEmphasis',
 'dosiomics_glszm_LargeAreaEmphasis',
 'dosiomics_glszm_LargeAreaHighGrayLevelEmphasis',
 'dosiomics_glszm_LargeAreaLowGrayLevelEmphasis',
 'dosiomics_glszm_LowGrayLevelZoneEmphasis',
 'dosiomics_glszm_SizeZoneNonUniformity',
 'dosiomics_glszm_SizeZoneNonUniformityNormalized',
 'dosiomics_glszm_SmallAreaEmphasis',
 'dosiomics_glszm_SmallAreaHighGrayLevelEmphasis',
 'dosiomics_glszm_SmallAreaLowGrayLevelEmphasis',
 'dosiomics_glszm_ZoneEntropy',
 'dosiomics_glszm_ZonePercentage',
 'dosiomics_glszm_ZoneVariance',
 'dosiomics_ngtdm_Busyness',
 'dosiomics_ngtdm_Coarseness',
 'dosiomics_ngtdm_Complexity',
 'dosiomics_ngtdm_Contrast',
 'dosiomics_ngtdm_Strength',
 'dosiomics_shape_Elongation',
 'dosiomics_shape_Flatness',
 'dosiomics_shape_LeastAxisLength',
 'dosiomics_shape_MajorAxisLength',
 'dosiomics_shape_Maximum2DDiameterColumn',
 'dosiomics_shape_Maximum2DDiameterRow',
 'dosiomics_shape_Maximum2DDiameterSlice',
 'dosiomics_shape_Maximum3DDiameter',
 'dosiomics_shape_MeshVolume',
 'dosiomics_shape_MinorAxisLength',
 'dosiomics_shape_Sphericity',
 'dosiomics_shape_SurfaceArea',
 'dosiomics_shape_SurfaceVolumeRatio',
 'dosiomics_shape_VoxelVolume',
 'radiomics_firstorder_10Percentile',
 'radiomics_firstorder_90Percentile',
 'radiomics_firstorder_Energy',
 'radiomics_firstorder_Entropy',
 'radiomics_firstorder_InterquartileRange',
 'radiomics_firstorder_Kurtosis',
 'radiomics_firstorder_Maximum',
 'radiomics_firstorder_Mean',
 'radiomics_firstorder_MeanAbsoluteDeviation',
 'radiomics_firstorder_Median',
 'radiomics_firstorder_Minimum',
 'radiomics_firstorder_Range',
 'radiomics_firstorder_RobustMeanAbsoluteDeviation',
 'radiomics_firstorder_RootMeanSquared',
 'radiomics_firstorder_Skewness',
 'radiomics_firstorder_TotalEnergy',
 'radiomics_firstorder_Uniformity',
 'radiomics_firstorder_Variance',
 'radiomics_glcm_Autocorrelation',
 'radiomics_glcm_ClusterProminence',
 'radiomics_glcm_ClusterShade',
 'radiomics_glcm_ClusterTendency',
 'radiomics_glcm_Contrast',
 'radiomics_glcm_Correlation',
 'radiomics_glcm_DifferenceAverage',
 'radiomics_glcm_DifferenceEntropy',
 'radiomics_glcm_DifferenceVariance',
 'radiomics_glcm_Id',
 'radiomics_glcm_Idm',
 'radiomics_glcm_Idmn',
 'radiomics_glcm_Idn',
 'radiomics_glcm_Imc1',
 'radiomics_glcm_Imc2',
 'radiomics_glcm_InverseVariance',
 'radiomics_glcm_JointAverage',
 'radiomics_glcm_JointEnergy',
 'radiomics_glcm_JointEntropy',
 'radiomics_glcm_MCC',
 'radiomics_glcm_MaximumProbability',
 'radiomics_glcm_SumAverage',
 'radiomics_glcm_SumEntropy',
 'radiomics_glcm_SumSquares',
 'radiomics_gldm_DependenceEntropy',
 'radiomics_gldm_DependenceNonUniformity',
 'radiomics_gldm_DependenceNonUniformityNormalized',
 'radiomics_gldm_DependenceVariance',
 'radiomics_gldm_GrayLevelNonUniformity',
 'radiomics_gldm_GrayLevelVariance',
 'radiomics_gldm_HighGrayLevelEmphasis',
 'radiomics_gldm_LargeDependenceEmphasis',
 'radiomics_gldm_LargeDependenceHighGrayLevelEmphasis',
 'radiomics_gldm_LargeDependenceLowGrayLevelEmphasis',
 'radiomics_gldm_LowGrayLevelEmphasis',
 'radiomics_gldm_SmallDependenceEmphasis',
 'radiomics_gldm_SmallDependenceHighGrayLevelEmphasis',
 'radiomics_gldm_SmallDependenceLowGrayLevelEmphasis',
 'radiomics_glrlm_GrayLevelNonUniformity',
 'radiomics_glrlm_GrayLevelNonUniformityNormalized',
 'radiomics_glrlm_GrayLevelVariance',
 'radiomics_glrlm_HighGrayLevelRunEmphasis',
 'radiomics_glrlm_LongRunEmphasis',
 'radiomics_glrlm_LongRunHighGrayLevelEmphasis',
 'radiomics_glrlm_LongRunLowGrayLevelEmphasis',
 'radiomics_glrlm_LowGrayLevelRunEmphasis',
 'radiomics_glrlm_RunEntropy',
 'radiomics_glrlm_RunLengthNonUniformity',
 'radiomics_glrlm_RunLengthNonUniformityNormalized',
 'radiomics_glrlm_RunPercentage',
 'radiomics_glrlm_RunVariance',
 'radiomics_glrlm_ShortRunEmphasis',
 'radiomics_glrlm_ShortRunHighGrayLevelEmphasis',
 'radiomics_glrlm_ShortRunLowGrayLevelEmphasis',
 'radiomics_glszm_GrayLevelNonUniformity',
 'radiomics_glszm_GrayLevelNonUniformityNormalized',
 'radiomics_glszm_GrayLevelVariance',
 'radiomics_glszm_HighGrayLevelZoneEmphasis',
 'radiomics_glszm_LargeAreaEmphasis',
 'radiomics_glszm_LargeAreaHighGrayLevelEmphasis',
 'radiomics_glszm_LargeAreaLowGrayLevelEmphasis',
 'radiomics_glszm_LowGrayLevelZoneEmphasis',
 'radiomics_glszm_SizeZoneNonUniformity',
 'radiomics_glszm_SizeZoneNonUniformityNormalized',
 'radiomics_glszm_SmallAreaEmphasis',
 'radiomics_glszm_SmallAreaHighGrayLevelEmphasis',
 'radiomics_glszm_SmallAreaLowGrayLevelEmphasis',
 'radiomics_glszm_ZoneEntropy',
 'radiomics_glszm_ZonePercentage',
 'radiomics_glszm_ZoneVariance',
 'radiomics_ngtdm_Busyness',
 'radiomics_ngtdm_Coarseness',
 'radiomics_ngtdm_Complexity',
 'radiomics_ngtdm_Contrast',
 'radiomics_ngtdm_Strength',
 'radiomics_shape_Elongation',
 'radiomics_shape_Flatness',
 'radiomics_shape_LeastAxisLength',
 'radiomics_shape_MajorAxisLength',
 'radiomics_shape_Maximum2DDiameterColumn',
 'radiomics_shape_Maximum2DDiameterRow',
 'radiomics_shape_Maximum2DDiameterSlice',
 'radiomics_shape_Maximum3DDiameter',
 'radiomics_shape_MeshVolume',
 'radiomics_shape_MinorAxisLength',
 'radiomics_shape_Sphericity',
 'radiomics_shape_SurfaceArea',
 'radiomics_shape_SurfaceVolumeRatio',
 'radiomics_shape_VoxelVolume']

In [ ]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, balanced_accuracy_score, precision_score, recall_score, f1_score, log_loss
from sklearn.decomposition import PCA

def display_split_stats(split):
    stats = {j: list(split).count(j) for j in set(split)}
    for j, c in stats.items():
        print(f"\t {j}: {c} ({int(100*c/len(split))}%)")

def cross_validation(X, Y, kfold=3, bootstrap=None, feature_selection=None, feature_reduction_N=None):
    """
    Perform cross validation training and return classification metrics as dict

    args
        X (numpy.ndarray) training data input of shape (n_samples, n_features)
        Y (numpy.ndarray) training data expected output of shape (n_samples)
        kfold (int) number of folds
        bootstrap (int) number of time to eprform the training with random splitting, if None apply k-fold
        feature_selection (str) feature selection method to apply (see sklearn)
        feature_reduction_N (int) number of dimension to reduce data into using PCA
    """

    metrics = []
    reductor = []
    if bootstrap:
        raise NotImplementedError() #TODO
    else:
        kf = KFold(n_splits=kfold)
        for i, (train_index, test_index) in enumerate(kf.split(X)):
            x_train, y_train = X[train_index], Y[train_index]
            x_test, y_test = X[test_index], Y[test_index]

            # print("fold ", i+1)
            # print("train:")
            # display_split_stats(y_train)
            # print("test:")
            # display_split_stats(y_test)

            if feature_reduction_N:
                print(f"transforming input from {x_train.shape[1]} to {feature_reduction_N} dimensions..")
                reduc = PCA(n_components=feature_reduction_N, random_state=0)
                reduc.fit(x_train)
                x_train = reduc.transform(x_train)
                x_test = reduc.transform(x_test)
                reductor.append(reduc)

            clf = LogisticRegression(random_state=0, verbose=0)
            clf.fit(x_train, y_train)
            y_pred = clf.predict(x_test)
            y_pred_proba = clf.predict_proba(x_test)
            metrics.append({
                "acc": accuracy_score(y_test, y_pred),
                "auc": roc_auc_score(y_test, y_pred),
                "balanced_accuracy": balanced_accuracy_score(y_test, y_pred),
                "precision": precision_score(y_test, y_pred, zero_division=0),
                "recall": recall_score(y_test, y_pred, zero_division=0),
                "f1_score": f1_score(y_test, y_pred, zero_division=0),
                "log_loss": log_loss(y_test, y_pred_proba),
            })
    return metrics, reductor

## 001-001

In [8]:
radiomics_df = df[df["features"].isin(["radiomics", "clinical"])]
print(radiomics_df["class"].unique())
print(radiomics_df["name"].unique())
print(radiomics_df["oar"].unique())

[nan 'shape' 'firstorder' 'glcm' 'gldm' 'glrlm' 'glszm' 'ngtdm']
['SEX' 'AGE' 'ST_STAG' 'ECOG' 'XEROSTOMIE' 'DYSPHAGIE' 'Elongation'
 'Flatness' 'LeastAxisLength' 'MajorAxisLength' 'Maximum2DDiameterColumn'
 'Maximum2DDiameterRow' 'Maximum2DDiameterSlice' 'Maximum3DDiameter'
 'MeshVolume' 'MinorAxisLength' 'Sphericity' 'SurfaceArea'
 'SurfaceVolumeRatio' 'VoxelVolume' '10Percentile' '90Percentile' 'Energy'
 'Entropy' 'InterquartileRange' 'Kurtosis' 'Maximum'
 'MeanAbsoluteDeviation' 'Mean' 'Median' 'Minimum' 'Range'
 'RobustMeanAbsoluteDeviation' 'RootMeanSquared' 'Skewness' 'TotalEnergy'
 'Uniformity' 'Variance' 'Autocorrelation' 'ClusterProminence'
 'ClusterShade' 'ClusterTendency' 'Contrast' 'Correlation'
 'DifferenceAverage' 'DifferenceEntropy' 'DifferenceVariance' 'Id' 'Idm'
 'Idmn' 'Idn' 'Imc1' 'Imc2' 'InverseVariance' 'JointAverage' 'JointEnergy'
 'JointEntropy' 'MCC' 'MaximumProbability' 'SumAverage' 'SumEntropy'
 'SumSquares' 'DependenceEntropy' 'DependenceNonUniformity'
 'DependenceNonUniformityNormalized' 'DependenceVariance'
 'GrayLevelNonUniformity' 'GrayLevelVariance' 'HighGrayLevelEmphasis'
 'LargeDependenceEmphasis' 'LargeDependenceHighGrayLevelEmphasis'
 'LargeDependenceLowGrayLevelEmphasis' 'LowGrayLevelEmphasis'
 'SmallDependenceEmphasis' 'SmallDependenceHighGrayLevelEmphasis'
 'SmallDependenceLowGrayLevelEmphasis' 'GrayLevelNonUniformityNormalized'
 'HighGrayLevelRunEmphasis' 'LongRunEmphasis'
 'LongRunHighGrayLevelEmphasis' 'LongRunLowGrayLevelEmphasis'
 'LowGrayLevelRunEmphasis' 'RunEntropy' 'RunLengthNonUniformity'
 'RunLengthNonUniformityNormalized' 'RunPercentage' 'RunVariance'
 'ShortRunEmphasis' 'ShortRunHighGrayLevelEmphasis'
 'ShortRunLowGrayLevelEmphasis' 'HighGrayLevelZoneEmphasis'
 'LargeAreaEmphasis' 'LargeAreaHighGrayLevelEmphasis'
 'LargeAreaLowGrayLevelEmphasis' 'LowGrayLevelZoneEmphasis'
 'SizeZoneNonUniformity' 'SizeZoneNonUniformityNormalized'
 'SmallAreaEmphasis' 'SmallAreaHighGrayLevelEmphasis'
 'SmallAreaLowGrayLevelEmphasis' 'ZoneEntropy' 'ZonePercentage'
 'ZoneVariance' 'Busyness' 'Coarseness' 'Complexity' 'Strength']
[nan 'inferior_pharyngeal_constrictor' 'mandible'
 'middle_pharyngeal_constrictor' 'parotid_gland_contra'
 'parotid_gland_ipsi' 'superior_pharyngeal_constrictor'
 'submandibular_gland_contra' 'submandibular_gland_ipsi' 'oral_cavity']

In [ ]:
import os, json
import numpy as np
import tqdm
from sklearn.preprocessing import normalize, scale, minmax_scale
import plotly.express as px

def pca_visualization(x, y):
    x = PCA(n_components=2, random_state=0).fit_transform(x)
    fig = px.scatter(x=x[:,0], y=x[:,1], color=y)
    fig.show()

def get_unique_combos(df, col1, col2):
    unique_combos = df[[col1, col2]].drop_duplicates()
    return list(unique_combos.itertuples(index=False, name=None))

exp_code = "001"
exp = [
    # parotid ipsi
    {"feature_reduction_N": None, "class": ["shape"], "oar": "parotid_gland_ipsi"},
    {"feature_reduction_N": None, "class": ["firstorder"], "oar": "parotid_gland_ipsi"},
    {"feature_reduction_N": None, "class": ['glcm', 'gldm', 'glrlm', 'glszm', 'ngtdm'], "oar": "parotid_gland_ipsi"},
    {"feature_reduction_N": None, "class": [], "oar": "parotid_gland_ipsi"}, # all classes

    # parotid contra
    {"feature_reduction_N": None, "class": ["shape"], "oar": "parotid_gland_contra"},
    {"feature_reduction_N": None, "class": ["firstorder"], "oar": "parotid_gland_contra"},
    {"feature_reduction_N": None, "class": ['glcm', 'gldm', 'glrlm', 'glszm', 'ngtdm'], "oar": "parotid_gland_contra"},
    {"feature_reduction_N": None, "class": [], "oar": "parotid_gland_contra"},
]

for exp_params in tqdm.tqdm(exp):
    # create experience name
    if len(exp_params["class"]) == 0:
        features_names = "all"
    else:
        features_names = "_".join(exp_params["class"])
    exp_name = f"{exp_code}_{exp_params['oar']}_{features_names}"

    # select data containing OARs
    exp_df = radiomics_df[(radiomics_df["oar"] == exp_params["oar"])]
    if len(exp_params["class"]) > 0:
        exp_df = exp_df[exp_df["class"].isin(exp_params["class"])]
    
    # build X,Y
    patients = exp_df["id"].unique()
    features = get_unique_combos(exp_df, "class", "name")
    X = [[exp_df[(exp_df["id"] == int(p)) & (exp_df["class"] == class_) & (exp_df["name"] == name_)]["value"].item() for class_, name_ in features] for p in patients]
    Y = [df[(df["id"] == int(p)) & (df["name"] == "XEROSTOMIE")]["value"].item() for p in patients]
    X = np.array(X, dtype=np.float32)
    Y = np.array(Y, dtype=np.float16).astype(dtype=np.int16)

    # normalize features
    # X = scale(X, axis=0)
    X = minmax_scale(X, axis=0)

    # print("X: ", X.shape)
    # print("Y: ", Y.shape)

    # pca_visualization(X, Y)

    # fit model
    metrics, _ = cross_validation(X, Y, kfold=3, feature_reduction_N=exp_params["feature_reduction_N"])

    # save results
    out_dir = os.path.join("./experiments", exp_code, exp_name)
    os.makedirs(out_dir, exist_ok=True)
    pandas.DataFrame(metrics).to_csv(os.path.join(out_dir, "metrics.csv"))

    # save exp params
    with open(os.path.join(out_dir, "params.json"), "w") as f:
        json.dump(exp_params, f)

  0%|          | 0/8 [00:00<?, ?it/s]

 12%|█▎        | 1/8 [00:01<00:11,  1.71s/it]

X:  (46, 14)
Y:  (46,)
fold  1
train:
	 0: 22 (73%)
	 1: 8 (26%)
test:
	 0: 11 (68%)
	 1: 5 (31%)
fold  2
train:
	 0: 23 (74%)
	 1: 8 (25%)
test:
	 0: 10 (66%)
	 1: 5 (33%)
fold  3
train:
	 0: 21 (67%)
	 1: 10 (32%)
test:
	 0: 12 (80%)
	 1: 3 (20%)

 25%|██▌       | 2/8 [00:03<00:10,  1.76s/it]

X:  (46, 18)
Y:  (46,)
fold  1
train:
	 0: 22 (73%)
	 1: 8 (26%)
test:
	 0: 11 (68%)
	 1: 5 (31%)
fold  2
train:
	 0: 23 (74%)
	 1: 8 (25%)
test:
	 0: 10 (66%)
	 1: 5 (33%)
fold  3
train:
	 0: 21 (67%)
	 1: 10 (32%)
test:
	 0: 12 (80%)
	 1: 3 (20%)

 38%|███▊      | 3/8 [00:07<00:14,  3.00s/it]

X:  (46, 75)
Y:  (46,)
fold  1
train:
	 0: 22 (73%)
	 1: 8 (26%)
test:
	 0: 11 (68%)
	 1: 5 (31%)
fold  2
train:
	 0: 23 (74%)
	 1: 8 (25%)
test:
	 0: 10 (66%)
	 1: 5 (33%)
fold  3
train:
	 0: 21 (67%)
	 1: 10 (32%)
test:
	 0: 12 (80%)
	 1: 3 (20%)

 50%|█████     | 4/8 [00:14<00:17,  4.48s/it]

X:  (46, 107)
Y:  (46,)
fold  1
train:
	 0: 22 (73%)
	 1: 8 (26%)
test:
	 0: 11 (68%)
	 1: 5 (31%)
fold  2
train:
	 0: 23 (74%)
	 1: 8 (25%)
test:
	 0: 10 (66%)
	 1: 5 (33%)
fold  3
train:
	 0: 21 (67%)
	 1: 10 (32%)
test:
	 0: 12 (80%)
	 1: 3 (20%)

 62%|██████▎   | 5/8 [00:15<00:09,  3.32s/it]

X:  (46, 14)
Y:  (46,)
fold  1
train:
	 0: 22 (73%)
	 1: 8 (26%)
test:
	 0: 11 (68%)
	 1: 5 (31%)
fold  2
train:
	 0: 23 (74%)
	 1: 8 (25%)
test:
	 0: 10 (66%)
	 1: 5 (33%)
fold  3
train:
	 0: 21 (67%)
	 1: 10 (32%)
test:
	 0: 12 (80%)
	 1: 3 (20%)

 75%|███████▌  | 6/8 [00:17<00:05,  2.66s/it]

X:  (46, 18)
Y:  (46,)
fold  1
train:
	 0: 22 (73%)
	 1: 8 (26%)
test:
	 0: 11 (68%)
	 1: 5 (31%)
fold  2
train:
	 0: 23 (74%)
	 1: 8 (25%)
test:
	 0: 10 (66%)
	 1: 5 (33%)
fold  3
train:
	 0: 21 (67%)
	 1: 10 (32%)
test:
	 0: 12 (80%)
	 1: 3 (20%)

 88%|████████▊ | 7/8 [00:21<00:03,  3.17s/it]

X:  (46, 75)
Y:  (46,)
fold  1
train:
	 0: 22 (73%)
	 1: 8 (26%)
test:
	 0: 11 (68%)
	 1: 5 (31%)
fold  2
train:
	 0: 23 (74%)
	 1: 8 (25%)
test:
	 0: 10 (66%)
	 1: 5 (33%)
fold  3
train:
	 0: 21 (67%)
	 1: 10 (32%)
test:
	 0: 12 (80%)
	 1: 3 (20%)

100%|██████████| 8/8 [00:28<00:00,  3.53s/it]

X:  (46, 107)
Y:  (46,)
fold  1
train:
	 0: 22 (73%)
	 1: 8 (26%)
test:
	 0: 11 (68%)
	 1: 5 (31%)
fold  2
train:
	 0: 23 (74%)
	 1: 8 (25%)
test:
	 0: 10 (66%)
	 1: 5 (33%)
fold  3
train:
	 0: 21 (67%)
	 1: 10 (32%)
test:
	 0: 12 (80%)
	 1: 3 (20%)

# Analysis

In [ ]:
import os
import pandas
import plotly.express as px

path_ = r"C:\Users\bilel.guetarni\Desktop\ARTIX\experiments\001"

result_df = []
for exp in os.listdir(path_):
    metrics_df = pandas.read_csv(os.path.join(path_, exp, "metrics.csv"))
    metrics_df = metrics_df.drop(columns=["Unnamed: 0"])
    avg_metrics = metrics_df.mean().to_dict()
    for k, v in avg_metrics.items():
        result_df.append({"exp": exp, "metric": k, "value": v, "std": metrics_df.std().to_dict()[k]})

print(len(result_df))
result_df = pandas.DataFrame(result_df)

for metric in result_df["metric"].unique():
    metric_df = result_df[result_df["metric"] == metric]
    fig = px.bar(metric_df, x="exp", y="value", title=metric)
    fig.show()

56